### PR TITLE
[copy update] WD-6242 - update on `/landscape/managed`

### PR DESCRIPTION
**Pull request by pedoch**
## Done

- Copy update on `/landscape/managed`
- Add meta image

## QA

- Check out [the demo here](https://ubuntu-com-13195.demos.haus/landscape/managed) and compare it with the changes requested in [the copy doc](https://docs.google.com/document/d/1MycPWcmMveCZxrGtn7ASc0myWNxPzLTciHfQIA6kPZ4/edit#heading=h.rzaw32crpetv).

## Issue / Card

- [WD-6242](https://warthogs.atlassian.net/browse/WD-6242)

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

[WD-6242]: https://warthogs.atlassian.net/browse/WD-6242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by carkod — APPROVED** [review]
Thanks. LGTM

**Comment by pedoch** [comment]
@lyubomir-popov ping.

**Comment by lyubomir-popov** [comment]
padding-top should be shallow, we're working on a component to do that, for now please do it as it is done [here](https://ubuntu.com/ai/mlflow).

**Comment by pedoch** [comment]
> padding-top should be shallow, we're working on a component to do that, for now please do it as it is done [here](https://ubuntu.com/ai/mlflow).

@lyubomir-popov just to clarify, the image should have a shallow padding-top right? To give it some distance from the text.

**Comment by lyubomir-popov** [comment]
@pedoch sorry not the image - the headeer itself:
image

**Comment by lyubomir-popov** [comment]
shallow strip with no margin bottom wreapping a p-section as in the ai bubble page linked above

**Comment by pedoch** [comment]
@lyubomir-popov the header in the linked page doesn't follow the pattern you just described but I have applied the changes as described: a shallow `p-strip` with `no-padding--bottom`, wrapping a `p-section`

**Comment by lyubomir-popov** [comment]
LGTM thanks @pedoch! Nice work.

**Pull request merged**
