### PR TITLE
[copy update] /landscape/managed

### PR DESCRIPTION
**Pull request by mtruj013**
## Done

- [Updated copy as per [doc](https://docs.google.com/document/d/1tU1z9PUm_kSwGJEsopJibE4gI8Gfv_3Dw_qN2_io_ao/edit#)
- Drive bys:
  - Fixed section alignment in /landscape/managed to match [design](https://github.com/canonical/ubuntu.com/pull/12812#issuecomment-1523023623) 

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: https://ubuntu-com-12916.demos.haus/landscape/install
- See that requested changed have been made
- View the site locally in your web browser at: https://ubuntu-com-12916.demos.haus/landscape/managed
- See that the page matches design  

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-3987

### CODE REVIEW

**Comment by juanruitina** [comment]
The /install page could use some UX work, but I understand that's out of scope. Copy changes are fine.

The visual for /managed matches the mockup as far as I can see.

LGTM!

**Comment by lyubomir-popov** [comment]
@mtruj013 can you replace the main content with this: https://pastebin.canonical.com/p/N2SvbvbT8j/

(small fixes) - and if you update to latest 4.0 that will be released today, the bottom section will turn white:
ubuntu-com-12916 demos haus_landscape_managed

**Comment by mtruj013** [comment]
@lyubomir-popov could you take another look?

**Comment by lyubomir-popov** [comment]
@mtruj013 I think the build is stuck, can you refres hit?

**Comment by nottrobin** [comment]
@lyubomir-popov demo working again

**Comment by lyubomir-popov** [comment]
Thanks @nottrobin!

**Comment by lyubomir-popov** [comment]
@mtruj013 I pushed an update to make the medium breakpoint look like this:
image

**Pull request merged**
