### PR TITLE
WD-16633 Rebranded embedded

### PR DESCRIPTION
**Pull request by muhammad-ali-pk**
## Done

- Rebranded ubuntu.com/embedded

## QA
- View the site in your web browser at: https://ubuntu-com-14544.demos.haus/embedded
    - Be sure to test on mobile, tablet and desktop screen sizes
- Match the website with Design and Copydoc.
  - [Design](https://www.figma.com/design/1CdIT6TV3ASf55GsnQcwXg/Internet-of-Things?node-id=2001-15115&node-type=frame&t=usaNja4yG3s3e7ZI-0)
  - [Copydoc](https://docs.google.com/document/d/15Tz87YRg4SnX4DWGOSl2TDTHLSStJoma879xHnF0nuo)

## Issue / Card

Fixes #[16633](https://warthogs.atlassian.net/browse/WD-16633)

### CODE REVIEW

**Comment by eliman11** [comment]
Thanks @muhammad-ali-pk! Looks great, a couple quick comments: 
- [ ] Change to US spelling: 'unauthorized' under 'Scanning' 
- [ ] Could we link 'Contact us' here to open the modal?
Screenshot 2024-12-06 at 11 44 45

- [ ] Sorry for the confusion! The HTML tags on this page are a little trickier, I've annotated on Figma what the right ones should be

**Comment by muhammad-ali-pk** [comment]
Thanks @eliman11 ! All done!

**Comment by eliman11** [comment]
Looks good, thanks @muhammad-ali-pk!

**Comment by mattea-turic** [comment]
thanks @muhammad-ali-pk ! 

for this section: 
Screenshot 2024-12-10 at 09 48 46
- [ ] could you wrap the image in a shallow pls? it looks off to me where the spacing isn't even – and if this doesn't look great either, I'll probably ask if you can remove the shallows from both :')

For this section:
Screenshot 2024-12-10 at 09 50 37
- [ ]  since there's no link for the second item, could you allow for breaks of the hr between each of the items (and remove from docker entirely)

all else is good!

**Review by akbarkz — APPROVED** [review]

**Pull request merged**
