### PR TITLE
WD-12061 - rebrand /cloud/multi-cloud

### PR DESCRIPTION
**Pull request by lizzochek**
## Done

Rebrand /cloud/multi-cloud. No content was changed, layout only

## QA

- [demo link](https://ubuntu-com-14082.demos.haus/cloud/multi-cloud)
- [figma](https://www.figma.com/design/NpI2wzW86XXPWxsSeomYfy/u.c%2Fcloud?node-id=31-1589&t=JDqOlKdc8TNDstzv-1)
- View the site on demo
- Run through the following [QA steps](https://discourse.canonical.com/t/qa-steps/152)
- Check that the page is correct according to figma

## Issue / Card
[WD-12061](https://warthogs.atlassian.net/browse/WD-12061)

[WD-12061]: https://warthogs.atlassian.net/browse/WD-12061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by lyubomir-popov** [comment]
@lizzochek - mostly looks good, thanks. -1 for now as the icons need to be in containers with a shaded background and 2:3 aspect ratio - see the design.

image
image

also, the logo sizes are way off - pls use rems when sizing, so that the change of the value of rem that happens at 1680px won't affect them:
image

here's how you can do it:
image

the ret looks good, well done!

**Comment by lyubomir-popov** [comment]
same comment about p-rule as on the other pr - please remove them, so we have consistent distance between hrs and text. We will deprecate them in vanilla 
image

**Comment by immortalcodes** [comment]
image
I guess we are skipping these images for now. Just to confirm on this

**Comment by immortalcodes** [comment]
You have done a nice job! Just very minute nit-picking from my side. Thank you for your good work.

**Comment by lizzochek** [comment]
Yea, we are skipping images until we get assets

**Review by immortalcodes — CHANGES_REQUESTED** [review]

**Comment by immortalcodes** [comment]
LGTM.

**Review by immortalcodes — APPROVED** [review]

**Pull request merged**
