### PR TITLE
Nojs meganav

### PR DESCRIPTION
**Pull request by petesfrench**
https://ubuntu-com-13141.demos.haus/navigation

## Done

- [List of work items including drive-bys - remember to add the why and what of this work.]

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Test without Javascript 
    - Be sure to test on mobile, tablet and desktop screen sizes

## Issue / Card

Fixes #

## Screenshots

[If relevant, please include a screenshot.]

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

### CODE REVIEW

**Comment by petesfrench** [comment]
@juanruitina I have applied the changes we spoke about, could you take another look please?

**Comment by juanruitina** [comment]
This is exactly what I expected. Please check the links on the top navigation when javascript is off; there's some that don't work. Other than that, this looks good to me.

**Comment by petesfrench** [comment]
> This is exactly what I expected. Very minor things:
> 
> * ~~Please check the links on the top navigation when javascript is off; there's some that don't work.~~
> *~~ Change URL to /navigation~~
> * ~~Change page title to "Navigation | Ubuntu"~~
> 
> We will need to look into how it looks on mobile, but on desktop this looks good to me.

Updated accordingly. 

I think with mobile we should aim to keep it changes to a minimum (ie. not a lot of dev/ux time). Users with JS disabled are extremely low and mobile users are also a minority. So it is a very niche edge case.

**Comment by juanruitina** [comment]
Yeah, don't expect mobile users to have JS off, but let's try to make it at least good enough given smaller viewports can also happen on desktop.

A couple of minor things, when JS is off:

* Hide the chevrons, given that they are not dropdowns anymore.
* On the smaller viewports, the "Menu" should link to /navigation, and the "Search" icon to https://ubuntu.com/search

**Comment by petesfrench** [comment]
@juanruitina Can you take another look please?

**Comment by juanruitina** [comment]
Search button doesn't link to the search page on mobile for some reason.

I would also remove the extra padding to the right of the links in the navigation, no need for it without the chevrons.

**Comment by petesfrench** [comment]
@juanruitina I have addressed the comments you left above. Is there anything else or can this go for code&qa?

**Comment by juanruitina** [comment]
One very minor thing: please add a 2rem padding above ´.dropdown-window__sidenav-content´ so the list of links on the right aligns with the tabs on the left.

We will also need to check how this behaves once we add the sticky navigation, but I think it's good to merge now anyway.

**Comment by juanruitina** [comment]
- [ ] There are some misalignments on the bubble pages ("Canonical Ubuntu", "Products")

Screenshot 2023-09-27 at 17 59 18

- [ ] Something went wrong on mobile: the items don't span 100%, the "Back" icon is misaligned.

Screenshot 2023-09-27 at 18 00 36
Screenshot 2023-09-27 at 18 01 13

- Also on mobile, I need to tap twice on top of the top-level items ("Products", "Use cases"...) for them to open.

Let me know if you wanna pair to go through it all.

**Comment by juanruitina** [comment]
Another thing I just spotted: second level headings ("Featured", "Ubuntu OS"...) should be H3s (styling is correct).

**Comment by petesfrench** [comment]
@juanruitina Do you want to take another look or can I go ahead and merge?

**Comment by juanruitina** [comment]
This works well UX-wise, I'd like to further test it with the latest version of the meganav so feel free to merge to the feature branch, yes.

**Pull request merged**
