### PR TITLE
Build /18-04/aws

### PR DESCRIPTION
**Pull request by mtruj013**
## Done

- Built as per [doc](https://docs.google.com/document/d/1mZliSIg5yruIqcTbQwr_D2MNIonmlqnYdrUQzOmIqvE/edit#)
- Design is meant to match the rest of the pages in the 18-04 bubble, please compare against those

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: https://ubuntu-com-12915.demos.haus/18-04/aws
    - Be sure to test on mobile, tablet and desktop screen sizes
- See that the copy matches the doc
- See that the design matches the other 18-04 pages

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-4155

### CODE REVIEW

**Comment by juanruitina** [comment]
Can you adjust the webinars? Thumbnail first, then title linked with the chevron, then description. (This is the main change we are introducing at this point, that we need to apply to the live pages as well).

**Comment by carkod** [comment]
> Can you adjust the webinars? Thumbnail first, then title linked with the chevron, then description. (This is the main change we are introducing at this point, that we need to apply to the live pages as well).
> 
> Also, we need to update the thumbnail of the first webinar, [here it is in full res](https://drive.google.com/file/d/1DJtF8znyrvwR0Jh4-Lk91paJeYmYRpBB/view?usp=sharing).

I uploaded to assets server here is the link https://assets.ubuntu.com/v1/a8ecc110-ubuntu-18.04-end-standard-support.png

**Review by tbille — APPROVED** [review]
Update images and feel free to merge.

**Comment by mtruj013** [comment]
@juanruitina @julpal7 could y'all take a look when you can? I changed the spacing for the separators above the thumbnails as they didn't look right anymore with the new structure for the webinar, please lmk if you're happy with it

**Comment by julpal7** [comment]
[mtruj013](https://github.com/mtruj013) link to the demo isn't working, I will look into it as soon as I can preview the demo.

**Comment by mtruj013** [comment]
@julpal7 @juanruitina demo should be working now if y'all could take a look

**Comment by mtruj013** [comment]
@juanruitina done, could you please update the label if you're happy with it?

**Comment by carkod** [comment]
I don't think you need to Released label anymore, because it's deploying directly to prod, I presume you haven't actually triggered any jenkins jobs?

**Pull request merged**
