### PR TITLE
Rename file to fix pricing/desktops navigation

### PR DESCRIPTION
**Pull request by carkod**
## Done

Fix pricing/desktops navigation

## QA

Go to https://ubuntu-com-12503.demos.haus/pricing and click on the desktops navigation, it should work now with this fix

## Issue / Card

Fixes https://github.com/canonical/ubuntu.com/issues/12501

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

### CODE REVIEW

**Comment by tbille** [comment]
@carkod  Can you add a redirect from https://ubuntu.com/pricing/desktop to https://ubuntu.com/pricing/desktops just in case it was indexed?

**Comment by tbille** [comment]
@carkod can you also update the navigation so we are not always redirecting? It seems the link is still linking to `/pricing/desktop`

**Comment by carkod** [comment]
> @carkod can you also update the navigation so we are not always redirecting? It seems the link is still linking to `/pricing/desktop`

What do you mean? The navigation is currently pointing to /desktops.

Screenshot from 2023-02-03 14-33-39

**Comment by tbille** [comment]
From the pricing page, I see it's still linking to `/price/desktop`

**Comment by carkod** [comment]
> From the pricing page, I see it's still linking to `/price/desktop`

For me it's always been linking to /desktops on pricing page

image

**Comment by tbille** [comment]
hmmm that's weird. I don't have the same from your branch. Can you check this line on your branch: https://github.com/canonical/ubuntu.com/blob/main/navigation.yaml#L489

**Comment by carkod** [comment]
> hmmm that's weird. I don't have the same from your branch. Can you check this line on your branch: https://github.com/canonical/ubuntu.com/blob/main/navigation.yaml#L489

mm looks like Ant did something a few hours ago, but didn't deploy it https://github.com/canonical/ubuntu.com/commit/a8c8783d4a95601a4a23a00b2c9aa95f48241abf

**Comment by carkod** [comment]
Should be working now. Superseded by https://github.com/canonical/ubuntu.com/commit/a8c8783d4a95601a4a23a00b2c9aa95f48241abf

**Pull request closed without merging**
