### PR TITLE
23.10 release

### PR DESCRIPTION
**Pull request by akbarkz**
## Done

- Changes related to upgrading Ubuntu 23.04 to 23.10

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

### CODE REVIEW

**Comment by local-optimum** [comment]
Howdy folks, reviewing the site: https://ubuntu-com-13190.demos.haus/ today

Feedback from going through:

- [ ] https://ubuntu-com-13190.demos.haus/desktop/developers hasn't updated the release cadence graph for 23.10 (and dropped 22.10 from the visual)
- [ ] https://ubuntu-com-13190.demos.haus/about/release-cycle same image here (i think they're the same in the backend) needs updating.
- [ ] https://ubuntu-com-13190.demos.haus/desktop/developers hasn't got the new desktop bullet points for 23.10
- [ ] https://ubuntu-com-13190.demos.haus/download/desktop still has the lunar lobster icon
- [ ]  https://ubuntu-com-13190.demos.haus/download/raspberry-pi content is correct but the design is not great, the pi 5 image and certified image are too far away from the titles and also not aligned with each other. The supported devices table could do with more space between the device images and the LTS release as it feels very cluttered on the left.
- [ ] https://ubuntu-com-13190.demos.haus/download/cloud the device on here is way out of date, can we replace this?

**Comment by akbarkz** [comment]
@juanruitina can you please comment on the last two points from Oliver above? ⬆️

**Comment by juanruitina** [comment]
> * [ ]  https://ubuntu-com-13190.demos.haus/download/raspberry-pi content is correct but the design is not great, the pi 5 image and certified image are too far away from the titles and also not aligned with each other. The supported devices table could do with more space between the device images and the LTS release as it feels very cluttered on the left.
> * [ ]  https://ubuntu-com-13190.demos.haus/download/cloud the device on here is way out of date, can we replace this?

On the first item, I suggest to 1) place both images centered in a col-4 container, and 2) make the first column 40% wide so it's more balanced (also, please remove the paddings there, I think `row` added them). But these are visual adjustments, so @lyubomir-popov has the final say.

Second item is also visual: @lyubomir-popov do we have a more recent asset to replace the laptop [in the /download/cloud page](https://ubuntu-com-13190.demos.haus/download/cloud)?

**Comment by lyubomir-popov** [comment]
@juanruitina @akbarkz to properly address, we need to redesign a bit more of the page. I've designed it up to this point - feel free to just take that section for now. Then, once we get round to do the rest, this section won't need any rework. https://www.figma.com/file/wGMqsc7u32nWdKQQ9Rv8fP/Ubuntu.com-rebranding?type=design&node-id=1%3A786&mode=design&t=qjrMaooSIp4003Cl-1

image

**Comment by akbarkz** [comment]
> @juanruitina @akbarkz to properly address, we need to redesign a bit more of the page. I've designed it up to this point - feel free to just take that section for now. Then, once we get round to do the rest, this section won't need any rework. https://www.figma.com/file/wGMqsc7u32nWdKQQ9Rv8fP/Ubuntu.com-rebranding?type=design&node-id=1%3A786&mode=design&t=qjrMaooSIp4003Cl-1

Will be addressed in https://warthogs.atlassian.net/browse/WD-6705

**Comment by local-optimum** [comment]
Hey folks, looking at today's demo:

- [ ] The Ubuntu release cycle diagram still includes Ubuntu 22.10 which is out of support so needs to be dropped
- [ ] https://ubuntu-com-13190.demos.haus/download still has the lobster mascot (good to add to the automation flow)
- [ ] https://ubuntu-com-13190.demos.haus/download/iot NEW request - could we tweak the green button to say 'Install on Raspberry Pi' and drop the '2,3 or 4' since adding 5 to that would be too long
- [ ] The Pi page is still outstanding (but see it's being worked on above, although the mock up feels like the images are a bit large and intrusive.

**Review by anthonydillon — APPROVED** [review]
LGTM :+1:

**Pull request merged**
