### PR TITLE
Refresh /landscape/install

### PR DESCRIPTION
**Pull request by petesfrench**
## Done

- Refresh /landscape/install based on [copydoc](https://docs.google.com/document/d/1tU1z9PUm_kSwGJEsopJibE4gI8Gfv_3Dw_qN2_io_ao/edit#heading=h.yij8xaij9lcy)
- Removes unused styles

## QA

- Go to https://ubuntu-com-12675.demos.haus/landscape/install and check the content matches the [copydoc](https://docs.google.com/document/d/1tU1z9PUm_kSwGJEsopJibE4gI8Gfv_3Dw_qN2_io_ao/edit#heading=h.yij8xaij9lcy)

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-2448

### CODE REVIEW

**Comment by petesfrench** [comment]
@lyubomir-popov No, there was no design for this page, nor an issue to make a design. So I based the design off of other pages.

**Comment by petesfrench** [comment]
Desgin to be applied: https://www.figma.com/file/XWAr3VmcGPJKpk4KBTz1kB/U.com-pages?node-id=214%3A531&t=gQhNHyHJjFqJfVUO-1

**Comment by petesfrench** [comment]
@lyubomir-popov can you take another look at this please

**Comment by lyubomir-popov** [comment]
something's a bit broken here:

image

@ClementChaumel do we have a fix we can add here for the wrapping? As in temporarily add it locally, then remove it once fixed in vanilla
image

rest of QA here @petesfrench https://www.figma.com/file/XWAr3VmcGPJKpk4KBTz1kB/U.com-pages?node-id=418%3A596&t=pugacQfbCxwadQT1-1

**Comment by petesfrench** [comment]
> something's a bit broken here:
> 
> image
How can I replicate this @lyubomir-popov? I have tried on multiple screen sizes but it doesn't happen for me

**Comment by lyubomir-popov** [comment]
@pete this is broken on large screens onlny - above 1680 when the font size change kicks in. Something doesn't scale with rems, could it be values in pixels?

**Comment by petesfrench** [comment]
@lyubomir-popov I have updated accordingly, can you take another look please

**Comment by lyubomir-popov** [comment]
demo not working @petesfrench

**Comment by petesfrench** [comment]
@lyubomir-popov sorry, should be working now

**Comment by lyubomir-popov** [comment]
still a little off on large screens
image

**Comment by lyubomir-popov** [comment]
Can these be just paragraphs please? Helps with wrapping in the case of the long url too
image

**Comment by lyubomir-popov** [comment]
I would make the __content divs span all remaining columns - less wrappign of the commands:
image

**Comment by petesfrench** [comment]
> still a little off on large screens image

Hey @lyubomir-popov , I am not sure what I am supposed to change here

**Comment by petesfrench** [comment]
@lyubomir-popov I have applied what we spoke about in the call. I think it works for large and medium screens, but on small screens it wasn't clear to me how best to handle it. What do you think?

**Comment by carkod** [comment]
@lyubomir-popov can you take a look when you can?

**Comment by lyubomir-popov** [comment]
@petesfrench lokos almost perfect, but please insert `<hr class="u-no-margin--bottom">` above each step as in the design:
it is missing here:
image

**Comment by petesfrench** [comment]
@lyubomir-popov I have omitted the `u-no-margin--bottom` as it made things look quite cramped

**Comment by petesfrench** [comment]
@lyubomir-popov Could you take another look please?

**Comment by lyubomir-popov** [comment]
> @lyubomir-popov I have omitted the `u-no-margin--bottom` as it made things look quite cramped

if the text is inside an h5 or p, there will be .4rem of padding-top on it which should be enough. I think you should remove the margin bottom on the hrs. Also, there seems to be a shallow strip around some - thst should be there to separate individual steps, but it should have u-no-padding—top so it doesn’t add space between the text and hr. And finally, I would remove the numbers and lines on mobile, it will read better IMO.

**Comment by lyubomir-popov** [comment]
too much space above quick and manual install

366A2FD8-B4A1-4239-9662-961F533D0666

numbers and hrs can be hidden on mobile

98752590-44FA-4EEF-AB1A-18F7F21BE646

**Comment by petesfrench** [comment]
@lyubomir-popov Can you take a look please? Rajan has asked to get this up today

**Comment by lyubomir-popov** [comment]
@bartaz was the wrapping fix released? If it is, @petesfrench can you please merge this after the vanilla dependancy has been updated o avoid going live with this: 
image

**Comment by petesfrench** [comment]
@lyubomir-popov Yes, I have [this PR](https://github.com/canonical/ubuntu.com/pull/12742) open for the vanilla update and will rebase once that is merged

**Comment by lyubomir-popov** [comment]
@petesfrench great, please update, rebase and we're ready to publish. I've given a +1. Thanks for your patience on this!

**Review by tbille — APPROVED** [review]

**Pull request merged**
