### PR TITLE
switch steps 1 and 2 of server download

### PR DESCRIPTION
**Pull request by sowasred2012**
## Done

- Swapped steps 1 and 2 of /download/server according to copy doc: https://docs.google.com/document/d/1Qob4Ni_y1ffIdSWqaw2xH0dxiHZQmkRGP5nuoBhIfyM/edit#heading=h.w944gtee0h1h

## QA

- Visit https://ubuntu-com-11930.demos.haus/download/server
- See that step 1 is now "Manual server installation" and step 2 is now "Instant Ubuntu VMs", and make sure you can navigate back and forth between the steps

## Issue / Card

Fixes https://github.com/canonical/web-squad/issues/5235

### CODE REVIEW

**Comment by davegoddard42** [comment]
LGTM @sowasred2012. I'd like PdM sign off on this too.

@lechsandecki - could you take a look at the [demo here](https://ubuntu-com-11930.demos.haus/download/server) and make sure you're happy with the switch? I've spoken to @caldav about monitoring the numbers here and we're good to go. David Callé also suggested renaming the "Option 2: Instant Ubuntu VMs" button/tab to read "Option 2: Virtual Server Download" - this way the options seem complementary to each other. I think it makes sense. Thoughts?

cc @cpaelzer

**Comment by sowasred2012** [comment]
Marking as blocked, we need PdM input, and confirmation on what redirects to use.

**Comment by davegoddard42** [comment]
Please create a new URL - /download/server/multipass that points to Multipass tab (option 2). The URL doesn't need to change when a user clicks the "tab" on the server page.

Also, create two redirects:
- download/server/step1 sends users to /download/server/multipass
- download/server//step2 sends users to /download/server

**Review by carkod — APPROVED** [review]
LGTM, but maybe the content structure in the copy doc needs to be swapped

**Comment by davegoddard42** [comment]
LGTM @sowasred2012

**Review by carkod — APPROVED** [review]
LGTM

**Pull request merged**
