### PR TITLE
Updated cookie policy to v3.6.3

### PR DESCRIPTION
**Pull request by samhotep**
## Done

- Updated the coookie policy to v3.6.3

## QA

- View the demo in an incognito web browser
- **Before** accepting cookies, 
  - Open developer tools and in the console type in `dataLayer`
  - There should be a `{"consent", "default"}` object in the dataLayer
- **After** accepting cookies, 
  - There should be a `{"consent", "update"}` object in the dataLayer

### CODE REVIEW

**Comment by laszlokajtar** [comment]
@samhotep it seems to me that GTM script starts before consent initialization

**Review by steverydz — APPROVED** [review]
LGTM 👍

**Comment by samhotep** [comment]
> @samhotep it seems to me that GTM script starts before consent initialization

Please try again now

**Comment by laszlokajtar** [comment]
@samhotep lgtm!

**Pull request merged**
