### PR TITLE
Build why-openstack page

### PR DESCRIPTION
**Pull request by minkyngkm**
## Done

- Build page on `/openstack/why-openstack`

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
- Compare page against [copy doc](https://docs.google.com/document/d/1StqylVToo1URkhLvNfl17vZ52H35fXCVOR1aMKG1aGU/edit#)
- Demo : https://ubuntu-com-11992.demos.haus/openstack/why-openstack

## Issue / Card

Fixes [#5823](https://github.com/canonical/web-squad/issues/5823)

## Screenshots
Why OpenStack | Ubuntu (2022-09-01 10-51-50)

### CODE REVIEW

**Review by anthonydillon — CHANGES_REQUESTED** [review]
Thanks @minkyngkm some suggestions in the code and QA issues below

## QA
- Don't we want this page in the sub-navigation?
- Some missing links which you are aware of
- I have suggested a different image for the webinar section in the copy doc

**Comment by minkyngkm** [comment]
Thanks @anthonydillon for reviewing!🙏🏻
- Don't we want this page in the sub-navigation? ➡️ this was asked in the [brief](https://docs.google.com/document/d/1ppfMr1ZAUl4D7B5TaWx0jwiTC_SsyY4ZufADeQCtVuc/edit?disco=AAAAfH4R6as). 
- Some missing links which you are aware of ➡️  yep still waiting for the url.. 
- I have suggested a different image for the webinar section in the copy doc ➡️  I will update it  when I get the right webinar link

**Review by anthonydillon — APPROVED** [review]
LGTM :+1: once we have to comments in the copy doc and link addressed.

**Comment by anakritskaya** [comment]
Hi! Let me know if this is the right way to place comments after reviewing the page.
1. First section **OpenStack: what is it and why do you need it?**: is it possible to add some visual elements to the bottom part of this section, not just to the top cause it looks a bit too blank? e.g. https://ubuntu.com/openstack/managed
2. Add grey background to the section **An Introduction to OpenStack**
3. Between the section **OpenStack: what is it and why do you need it?** and **A business guide to cloud migration** could you please add one element with the case study? It should look like a horizontal stripe, lower than the usual section, with background being a picture from the case study and some text on it? Here is what I mean (light blue strip): https://www.ibm.com/eg-en/it-infrastructure/power

I am attaching 2 images as references for you as well. 
Image 1: Firmus case study_for LP
Image 2 in case the first one looks too bulky in terms of text: 
Firmus case study_for LP_v2

Link for this section: https://pages.ubuntu.com/rs/066-EOV-335/images/Firmus+Case+study.pdf+?_ga=2.233998550.99652456.1662360547-1232158778.1655899900

4. For this section with the case study could you please provide a link that will lead directly to this part of the page? Usually it's with #. We will need to use this link for some paid ads promotions that have to lead to the case study part of the website
5. Get in touch: does it have the form ID - ﻿4578? Just to double check

**Comment by petesfrench** [comment]
@spencerbygraves could you take a look at this please?

**Comment by spencerbygraves** [comment]
@petesfrench yes, will take a look...

**Comment by spencerbygraves** [comment]
Hi @anakritskaya. For the case study element, we don't have a vanilla component with a background image but we can achieve the below with existing ones. Thanks.

image

**Pull request merged**
