### PR TITLE
Update /hpe page

### PR DESCRIPTION
**Pull request by petesfrench**
## Done

- builds /hpe page based on [copydoc](https://docs.google.com/document/d/1A2__NxIU6jFKprs5thPNtIPfOc7E9VhZEoPFu01lT_8/edit)

## QA

- Compare against copydoc

## Issue / Card

Fixes https://github.com/canonical/web-squad/issues/5894

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

### CODE REVIEW

**Comment by petesfrench** [comment]
@al-bakalova Can you take a look at this please. Specifically how the CTA at the top of the page takes you to another CTA at the bottom of the page. demo: https://ubuntu-com-12220.demos.haus/hpe

**Comment by al-bakalova** [comment]
Thanks for the heads-up, Pete! I have left some comments for Felipe in the copy doc.
@spencerbygraves - could you please take a look at this page and provide us with your feedback. I have visual concerns to share here:
- on the partnership pages, we usually have a "partner logo" + "Canonical/Ubuntu logo" image on top. Examples - Dell's and NVIDIA's pages. Is it a good idea to stick to that pattern here as well?
- The illustration facing "Ubuntu Tier1 operating system for HPE hardware" seems kind of heavy. I would suggest for us to make it smaller and have a consistent stroke with the rest of the illustrations.
Thank you!

**Comment by spencerbygraves** [comment]
Thanks @al-bakalova.

@petesfrench you can try this for the Canonical+HP logos at the top - https://assets.ubuntu.com/v1/c6a96b9a-logos-canonical+hpe.svg

And this for the hardware illustration - https://assets.ubuntu.com/v1/aec863e2-Off+the+shelf.svg

Cheers.

**Comment by spencerbygraves** [comment]
@petesfrench I think it would be better if all sub headings were h2. You could use h5/h2 for the section with "Resources", as we did on the /hpc page:

image

**Comment by petesfrench** [comment]
@spencerbygraves I have made those changes, could you take another look please

**Review by minkyngkm — COMMENTED** [review]
Looking great @petesfrench!

Just wondering if this page need to be added in the navigation?

Also, after QAing submission,  I got an error on [sentri](https://sentry.is.canonical.com/canonical/ubuntu-com/issues/29299/?query=is%3Aunresolved). It seems company and job title field are missing in the marketo form. 
image

**Review by minkyngkm — APPROVED** [review]

**Comment by petesfrench** [comment]
@minkyngkm Thanks for the feedback! I have asked in the copydoc about the navigation, but let's get this work out and we can address that in the future.

I have removed the 'title' and 'company' fields as the marketo form did not allow these

**Comment by petesfrench** [comment]
I spoke with Omar (who is covering for Felipe) and he explained that the form field 'Company' was not important, but 'Job title' was crucial. So I have re-implemented 'Job title' and added it to a field on marketo.
@minkyngkm Can you take another look please?

**Comment by minkyngkm** [comment]
LGTM! 👍

**Pull request merged**
