### PR TITLE
[22.10 update] on /download/server

### LINKED ISSUE #12163: [22.10 launch] /download/server
Brief: https://docs.google.com/document/d/11dBtq73CSqcnUH_6ki8nwMQipXFNkgEY_Du0nVb15Zk/edit
copy doc: https://docs.google.com/document/d/1Qob4Ni_y1ffIdSWqaw2xH0dxiHZQmkRGP5nuoBhIfyM/edit

Also please update /server according to
copy doc: https://docs.google.com/document/d/1vxLhtbjgPs9PCNEhr7fbhEoErCPMXYFfU4UTKH7Kbq4/edit

### PR DESCRIPTION
**Pull request by minkyngkm**
## Done

- 22.10 update  on /download/server
## QA
- Go to /download/server
- Compare page against [copy doc](https://docs.google.com/document/d/1Qob4Ni_y1ffIdSWqaw2xH0dxiHZQmkRGP5nuoBhIfyM/edit#heading=h.azl4arg09op)

## Issue / Card

Fixes #12163

### CODE REVIEW

**Comment by minkyngkm** [comment]
Question: 
The line 135 and 139, are they going to be updated automatically to the one written in the [copy doc](https://docs.google.com/document/d/1Qob4Ni_y1ffIdSWqaw2xH0dxiHZQmkRGP5nuoBhIfyM/edit?disco=AAAAhLw0yz8)?

**Comment by carkod** [comment]
> Question: The line 135 and 139, are they going to be updated automatically to the one written in the [copy doc](https://docs.google.com/document/d/1Qob4Ni_y1ffIdSWqaw2xH0dxiHZQmkRGP5nuoBhIfyM/edit?disco=AAAAhLw0yz8)?

If you rebase now, everything should look right, if not probably we need to change something (lts -> latest?)

**Comment by minkyngkm** [comment]
Thanks @carkod. I rebased it and it is showing as it is in the copy doc :) 

For the changes on the`/server` page, I think Andreu has been working on it with this [PR](https://github.com/canonical/ubuntu.com/pull/12189)

**Comment by carkod** [comment]
> Thanks @carkod. I rebased it and it is showing as it is in the copy doc :)
> 
> For the changes on the`/server` page, I think Andreu has been working on it with this [PR](https://github.com/canonical/ubuntu.com/pull/12189)

Andreu's PR doesn't look like it's related to 22.10? The changes are for 22.04

**Comment by carkod** [comment]
I am a bit confused about the image, because with the releases.yaml updated the page looks like this:

image

So this means that the main option to download is still 22.04, right? Because 22.10 is just an interim update, it's offered as a alternative release. So shouldn't we change the image below, not the top one?

**Comment by minkyngkm** [comment]
Thanks @carkod. The images have been updated! It's ready for a second look I think! Could you take a look please @sowasred2012? :)

**Review by sowasred2012 — APPROVED** [review]
LGTM - thanks Min!

**Pull request merged**
