### PR TITLE
WD-1466 add notice for posts written/updated over 1 year ago

### PR DESCRIPTION
**Pull request by pedoch**
## Done

- Added blog date notice for posts written/updated over a year ago.

## QA

- Check out the demo here and compare the following article to the screenshot below and in the task:
  - [LXD 5.0 LTS is now available](https://ubuntu-com-12833.demos.haus/blog/lxd-5-0-lts-is-now-available) 
    - this post is just over a year old and should say: "This article is more than **1 year old.**"
  - [Tutorials for everyone from everyone](https://ubuntu-com-12833.demos.haus/blog/tutorials-for-everyone-from-everyone) 
    - this post is just over 3 years old but was also updated about three years ago and should say: "This article was last updated **3 years ago.**"
  - [Top 6 projects from our Hackathon](https://ubuntu-com-12833.demos.haus/blog/top-6-projects-from-our-hackathon) 
    - this post is over a year old but was updated within the last year and should not have the blog date notice.
  - [Charmed Kubeflow is now available on AWS Marketplace](https://ubuntu-com-12833.demos.haus/blog/kubeflow-appliance-aws) 
    - this post is less than a year old and should not have the blog date notice.

## Issue / Card

- [WD-1466](https://warthogs.atlassian.net/browse/WD-1466)

## Screenshots

Screenshot 2023-03-17 at 10 15 16

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

[WD-1466]: https://warthogs.atlassian.net/browse/WD-1466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by evilnick** [comment]
Yay!

**Comment by juanruitina** [comment]
UX looks good to me! I wonder if we should increase the spacing slightly, but let's hear from @lyubomir-popov.

**Review by nottrobin — APPROVED** [review]
Fantastic work. Love the functionality and the look of it. :+1:

**Comment by nottrobin** [comment]
I suppose the only thing it's missing is a test. @pedoch if you want to be thorough and write one, I'm happy to help. Or if that will delay things too much, it's ok to merge. Your call.

**Comment by nottrobin** [comment]
@mtruj013: @pedoch and I wrote some tests for this. As an independent party here, would you mind reviewing the code and letting us know if you have any comments? Thanks :)

**Comment by anthonydillon** [comment]
I would expect to find feature tests in their own feature test file to separate concerns and more clear for future maintainers. WDYT?

**Comment by pedoch** [comment]
> I would expect to find feature tests in their own feature test file to separate concerns and more clear for future maintainers. WDYT?

Yes, this makes sense. I'll move it to its own test file.

**Comment by mtruj013** [comment]
@lyubomir-popov could you take a look please?

**Pull request merged**
