### PR TITLE
Build `/18-04/ibm` page - WD-4010

### PR DESCRIPTION
**Pull request by pedoch**
## Done

- Build the `/18-04/ibm` page

## QA

- Check out this [demo here](https://ubuntu-com-12919.demos.haus/18-04/ibm) and compare its content with the [copy doc](https://docs.google.com/document/d/1a32P199a-kmn1BgeI6kb_IVhbFGDah3hxTXPpfWepug/edit#) and also the design with the existing other existing [/18-04/* pages](https://ubuntu.com/18-04)

## Issue / Card

- [WD-4010](https://warthogs.atlassian.net/browse/WD-4010)

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

[WD-4010]: https://warthogs.atlassian.net/browse/WD-4010?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by juanruitina** [comment]
Can you align the code for webinars with [MariaPaula's](https://github.com/canonical/ubuntu.com/pull/12915)? Same separator and heading (H3 with H5 styles). Thank you!

**Comment by pedoch** [comment]
@juanruitina done!

**Comment by julpal7** [comment]
@pedoch Thank you for your help with the demo. I've noticed a couple of minor issues:

1. 
Screenshot 2023-06-05 at 12 40 33<br>
Please remove the HR above the .png and fix the picture outline (it is not visible at the bottom).

2. 
Screenshot 2023-06-05 at 12 41 51<br>
Here as well, please remove the HR above and add an outline to the .png, the white is fading into the background.

3. 
To stay consistent with the existing /18-04/ pages, we need to add an HR above the "Get in touch" line.<br>
Screenshot 2023-06-05 at 12 43 29

Reference from [here](https://ubuntu.com/18-04): <br>
Screenshot 2023-06-05 at 12 45 01

Everything else seems to be in order (for mobile/tablet as well) and follows the copy doc.

**Comment by pedoch** [comment]
Hi @julpal7 I'll replace the images and add the outline. Are you fine with the dividers though? I added a little more space so they match [MariaPaula's PR](https://github.com/canonical/ubuntu.com/pull/12915) and I think it looks better now. Would you still like me to remove them?

**Comment by julpal7** [comment]
@pedoch Definitely, they look great now! Please update the label to Design +1 if you can, for some reason I'm unable to edit them.

**Comment by mtruj013** [comment]
@pedoch I added a class for the thumbnail border in my pr if you wanna wait for that one to be +1ed and merged so you can rebase and use it as well

**Comment by pedoch** [comment]
@julpal7 you can take a look at this now, everything should be good

**Pull request merged**
