### PR TITLE
Nvidia partners page

### PR DESCRIPTION
**Pull request by carkod**
## Done

Build Nvidia partners page

## QA

- Check https://ubuntu-com-12441.demos.haus/nvidia against [copy docs](https://docs.google.com/document/d/1DJ1FuEswAojPNSX9JCLcWJwy-va5VMzuuLGwSNM0lRY/edit#)
- Check https://ubuntu-com-12441.demos.haus/nvidia against [design ](https://www.figma.com/file/S6KvNUt0agl0bcbp6wjhnB/Partners?node-id=576%3A9683&t=mHdjBYcAY7pSpuxX-0)
- Check contact-us form works
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes

## Issue / Card

Fixes https://github.com/canonical/web-squad/issues/6062

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

### CODE REVIEW

**Comment by anthonydillon** [comment]
@carkod this should be unblocked now

**Comment by carkod** [comment]
Blocked by Felicia's review of the diagram https://docs.google.com/document/d/1DJ1FuEswAojPNSX9JCLcWJwy-va5VMzuuLGwSNM0lRY/edit#
Waiting for logos from Lyubo

**Comment by lyubomir-popov** [comment]
@carkod I provided the logo assets on the jira tickets, is there anything else still blocking this?

**Comment by carkod** [comment]
> @carkod I provided the logo assets on the jira tickets, is there anything else still blocking this?

Yes, I remembered now, did you do any updates on the pdf for Felicia?

**Comment by lyubomir-popov** [comment]
> Sorry, which JIRA ticket? I don't see it in [this one](https://warthogs.atlassian.net/browse/WD-674?atlOrigin=eyJpIjoiOTU5MTg4M2U2Yzc1NDZkYWJkNGUyYzQ5M2VmZjlmZjIiLCJwIjoiaiJ9)?

on this one: https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/970?modal=detail&selectedIssue=WD-1211&quickFilter=2549&assignee=70121%3A2a3deb76-aa64-401c-8df9-e4f9db00411c

**Comment by lyubomir-popov** [comment]
@carkod here's the diagram thumbnail: https://assets.ubuntu.com/v1/6b6e253a-diagram-nvidia.png
you are currently using the wrong one.

**Comment by lyubomir-popov** [comment]
@carkod QA here https://www.figma.com/file/S6KvNUt0agl0bcbp6wjhnB/Partners?node-id=793%3A3945&t=mx6VSzskdWD6dFi6-1

**Comment by lyubomir-popov** [comment]
@carkod do you need anything else from me to complete this pr?

**Comment by carkod** [comment]
> @carkod do you need anything else from me to complete this pr?

Yes, were you able to correct the cloud image? Has a line on top

nvidia-cloud-illustration (3)

**Review by anthonydillon — CHANGES_REQUESTED** [review]
QA issues:
- [x] The dynamic form errors if you fill it out and click Next
- [x] Missing the links in the "Fast. Secure. Best-in-class." section
- [x] The second sentence in the "Take the fast track with certified hardware" section does not match the copy doc
- [x] The "Get enterprise-grade support and software maintenance" section is missing a link in the text
- [x] The "AI-Ready platforms" section is missing the link in the text
- [x] Missing links at the bottom of "AI-Ready platforms" section
- [ ] The text in the images are very difficult to read on small screens. Can you add u0hide--small on them and show a list with the text instead?
image

**Comment by carkod** [comment]
> QA issues:
> 
> * [x]  The dynamic form errors if you fill it out and click Next
> * [x]  Missing the links in the "Fast. Secure. Best-in-class." section
> * [x]  The second sentence in the "Take the fast track with certified hardware" section does not match the copy doc
> * [ ]  The "Get enterprise-grade support and software maintenance" section is missing a link in the text
> * [ ]  The "AI-Ready platforms" section is missing the link in the text
> * [ ]  Missing links at the bottom of "AI-Ready platforms" section
> * [ ]  The text in the images are very difficult to read on small screens. Can you add u0hide--small on them and show a list with the text instead?
>   image

The last point I guess it's up to design? @lyubomir-popov any pointers? or you can add something in [Figma](https://www.figma.com/file/S6KvNUt0agl0bcbp6wjhnB/Partners?node-id=576%3A9683&t=mHdjBYcAY7pSpuxX-0) and I'll build it

**Comment by anthonydillon** [comment]
I mean something similar to the d3 release charts where we switch to text on small screens.

**Comment by carkod** [comment]
> I mean something similar to the d3 release charts where we switch to text on small screens.

Done

**Comment by lyubomir-popov** [comment]
@carkod much better, a cfew small tthings left - [QA in the same figma file](https://www.figma.com/file/S6KvNUt0agl0bcbp6wjhnB/Partners?node-id=909%3A3918&t=520uHiWbwuac5fX7-1)

**Review by anthonydillon — APPROVED** [review]
LGTM :+1: thanks for all the hard work on this page @carkod

**Comment by carkod** [comment]
> @carkod much better, a cfew small tthings left - [QA in the same figma file](https://www.figma.com/file/S6KvNUt0agl0bcbp6wjhnB/Partners?node-id=909%3A3918&t=520uHiWbwuac5fX7-1)

I don't see anymore design issues. @lyubomir-popov let me know if there is anything else that needs corrected.

**Comment by lyubomir-popov** [comment]
Approved, thanks for your patience with thi8s @carkod ! Really appreciated.

**Pull request merged**
