### PR TITLE
WD-2344 - Add real-time contact form

### PR DESCRIPTION
**Pull request by tbille**
## Done

- This PR is heavily inspired/copied from https://github.com/canonical/ubuntu.com/pull/12612
- Add contact form 
- Missing: 
  - [x] Google analytics event
  - [x] marketo ID
  - [x] How to add others field
  - [x] confirm URL I proposed: `/kernel/real-time/contact-us` instead of `/real-time-contact-us`

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/kernel/real-time/contact-us

## Issue / Card

Fixes WD-2344

### CODE REVIEW

**Comment by petesfrench** [comment]
I have update https://github.com/canonical/ubuntu.com/pull/12612 to handle 'Other' check boxes, you will want to add some like this for the input:
```
 <div class="js-other-container">
    <label class="p-checkbox">
      <input class="p-checkbox__input js-other-container__checkbox" type="checkbox" aria-labelledby="priority-workloads-other">
      <span class="p-checkbox__label" id="priority-workloads-other">Other</span>
    </label>
    <input type="text" id="priority-workloads-other-specified" class="js-other-container__input" placeholder="Please specify" style="opacity: 0; margin-top: .25rem;" aria-label="Other architecture">
  </div>
```

**Comment by petesfrench** [comment]
@tbille is this ready for review?

**Comment by tbille** [comment]
@petesfrench no not yet.  I need to update a few fields.
It seems I can't make the snippet that you shared work. Would love to get your help on this. Let me update the PR and I'll get to you.

**Comment by petesfrench** [comment]
@tbille Let's pair on it today if you have time, if not I'm happy to push changes to this branch. Should we make this a draft or remove the labels if it is not yet ready for review?

**Comment by tbille** [comment]
@petesfrench ok I just made all the updates. Do you mind having a look to it? Feel free to push on the branch since I won't be able to jump back on it today I think. The things that are missing are: 

- [ ] updating the google analytics event (asked marketing waiting for an answer)
- [ ]  Update other fields to make them appear on the page.

**Comment by tbille** [comment]
@petesfrench  not sure if you are still working on it, but it looks like there are some small spacing issues with the other fields: 
image

**Comment by tbille** [comment]
nice one, it looks good now.

@petesfrench I haven't played with marketo is it normal that on localhost when I submit I get:

```
{
  "error": "There was an issue submitting the form."
}
```

**Comment by petesfrench** [comment]
@tbille I believe this is because you are lacking the appropriate .env variables, here is what I have in mine: https://pastebin.canonical.com/p/pGQwxDQV6q/

**Comment by tbille** [comment]
@petesfrench ok I confirm that it works!!
Do you mind doing a last check and approving the PR if you are happy with it?

**Review by petesfrench — APPROVED** [review]
LGTM

**Pull request merged**
