### PR TITLE
WD-4456 Update consulting pricing across the site

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done

- Update consulting pricing across the site

## QA

- Check that /openstack/consulting matches [the copy doc](https://docs.google.com/document/d/1f83OSIHVQGMjF7b0pZUKFvoubMGqi_b-OYbSpyhveX4/edit#)
- Check that /pricing matches [the copy doc](https://docs.google.com/document/d/1sXeOQ9eLq53NcfbrorYstHkZYTdut33jbN5LyHoDdYY/edit#)
- Check that /training matches [the copy doc](https://docs.google.com/document/d/1gyxy75qXC5Ta08o6Vnm13yK6aeN4qOnsETB2gZ4e0ZY/edit#)

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-4456

### CODE REVIEW

**Comment by nottrobin** [comment]
A few places in the demo say "Your premises or remote" instead of "Remote or your premises". But they all say "Remote or your premises" in the copy doc.

image

**Comment by anthonydillon** [comment]
@nottrobin thanks, fixed.

**Review by mtruj013 — APPROVED** [review]
LGTM

**Review by mtruj013 — APPROVED** [review]
LGTM

**Pull request merged**
