### PR TITLE
Add remaining meganav sections

### PR DESCRIPTION
**Pull request by sowasred2012**
## Done

- Added Products, Use Case, Community and Support sections to the meganav

## QA

- Visit https://ubuntu-com-12251.demos.haus/
- Open all of the dropdowns in the mega nav
- See that they work as expected:
  - Dropdowns should animate open and closed (they will switch instantly when navigating from one dropdown to another)
  - Some sections contain a side navigation, which should work
- Check the mobile view, see that it works

## Issue / Card

Fixes https://github.com/canonical/web-squad/issues/5983, https://github.com/canonical/web-squad/issues/5985, https://github.com/canonical/web-squad/issues/5986, https://github.com/canonical/web-squad/issues/5987

### CODE REVIEW

**Comment by fitojb** [comment]
Blue links on a dark background doesn’t seem very readable to me…

**Comment by sowasred2012** [comment]
@fitojb we took that into consideration when designing this, the blue we typically use in Vanilla was updated to make this meet WCAG level AA standards:

image

**Comment by fitojb** [comment]
@sowasred2012 The color contrast shouldn’t be the only criterion to consider when designing readable text. WCAG doesn’t consider the font weight, and it is _anæmic_. Using regular instead of light would help.

**Comment by sowasred2012** [comment]
> @sowasred2012 The color contrast shouldn’t be the only criterion to consider when designing readable text. WCAG doesn’t consider the font weight, and it is _anæmic_. Using regular instead of light would help.

I didn't say it was, I was addressing the original comment. Your point about font weight is valid though, we'll take that into consideration.

**Comment by carkod** [comment]
It's not a nuance for me, but I've noticed that if you have both "All canonical" opened and one of the navs on the left opened, you need to click twice to close the one you clicked. Here is a video:
[Screencast from 29-11-22 10:29:27.webm](https://user-images.githubusercontent.com/14939793/204505908-8f5edebc-77ac-4163-b71e-4d9ab2d1ca8f.webm)

**Review by carkod — APPROVED** [review]
Looking good

**Comment by sowasred2012** [comment]
> It's not a nuance for me, but I've noticed that if you have both "All canonical" opened and one of the navs on the left opened, you need to click twice to close the one you clicked.

Ah good point - I've got an issue to fix remaining bugs on this before merging the feature branch, I'll add this to that.

**Pull request merged**
