### PR TITLE
Subscription centre

### PR DESCRIPTION
**Pull request by sowasred2012**
## Done

- add /subscription-centre

## QA

- This is a feature branch, all QAs happened in PRs that were merged to this branch
- Demo: https://ubuntu-com-12345.demos.haus/subscription-centre?id= (reach out for a value)

### CODE REVIEW

**Comment by carkod** [comment]
@caldav can you take a look?

**Comment by sowasred2012** [comment]
@caldav bump on this - can this be merged and deployed?

**Comment by anthonydillon** [comment]
Still waiting on a review from the Marketo Freelancer.

**Comment by Beatrijsb** [comment]
Hi! @caldav and I gathered feedback on this first version of the design of the subscription centre. I wrote down the points below, does that work? Please let me know if it's better to provide it in a different way/format instead. Thank you in advance!

- Bottom of the page: can the 2 buttons go above the fold? Now you don't really see them when landing on the page. Maybe removing the whitespace 
- Can we add the text about the privacy policy that's in the current subscription center near the "update prefs" button? Text: In submitting this form, I confirm that I have read and agree to [Canonical’s Privacy Notice](https://ubuntu.com/legal/data-privacy/newsletter) and [Privacy Policy](https://ubuntu.com/legal/data-privacy).
- Spelling: Can "Cloud and Infrastructure" be changed to "Cloud & Infrastructure" so that it aligns with the other headers? Furthermore there is an "Ubutnu" in Ubuntu & Linux
- Is there a way to display the requestor's email address (not adjustable) somewhere at the top?
- For the clusters with "sub-topics": Is there a way to opt-in for the whole block at the toggle? E.g. everything within hardware without having to click 6 boxes.
- Optin box: please change the text to: "I agree to receive information about Canonical’s products and services."
- Can we hide the search bar for our MVP to go live? We're not really satisfied with it yet but might want to bring it back later on. 
- Can we keep the subtitle we had in the old subscription center? (example: https://pages.ubuntu.com/Subscription-preferences.html?mkt_unsubscribe=1)  So under "Subscription center" we would like to add "Tailor your email preferences"
- Above the optin box and instead of the search bar, can you place the following: Select your areas of interest below to regularly receive informative emails about relevant product announcements, webinars and events, case studies, and more. You can update your preferences here anytime. (see added screenshot of how this 
Screenshot (111)
could look)
- Ideally, when the uncheck the main optin box at the top, the rest should go grey below (the clusters with subtopics).

**Comment by petesfrench** [comment]
Hi @Beatrijsb, I am going to run any design/ux changes past one of the designers/uxers on our team to see how best to implement it ex. the privacy policy text etc.
1 & 2. I will talk with design/ux
3. Yes, I will update these now. And "Ubuntu & Linux" is what was detailed in [this document](https://miro.com/app/board/uXjVOtXFmLQ=/) but can be changed 
4. We can include it, but had been omitted for security concerns as the page is access through a URL string not our SSO. But if David is happy having it, this can be easily implemented. It will need some design advice though.
5. The time allocated to work on this project is over, a request like this would have to have been made earlier on. Or can be made a separate issue to be tackled later.
6, 7, 8, 9. I will update it now
10. Same as mentioned above, their is not significant time allocated to work on this right now. I think the best thing will be to create a new request with the sites tribe to work on the new features, but expect it to take some time.

**Comment by al-bakalova** [comment]
Hello there, here's a link to the reviewed mockup: https://www.figma.com/file/XtTjD7N3QqQq2WGjUp0qDq/Subscription-Centre?node-id=202%3A502&t=BLPYSx4IgiwhNjZe-1

When it comes to point 2, please do not change the position of the buttons. This is a pattern that we do not use currently. What is more, the Update button belongs to the same area where the Privacy policy is. That being said, these are usually at the bottom of the form.

Waiting for your feedback. Thanks!

**Comment by Beatrijsb** [comment]
Thank you both @petesfrench and @al-bakalova for taking the time to implement almost all of the points above! It looks great and we're excited to bring it live and start testing on this version of the subscription center.

In the future, we would want to have another look at point 4 (showing email address as requested by Thibaut) and 5 (select all option per toggle category). But we'll make sure to raise a separate ticket for that. @caldav FYI

**Comment by petesfrench** [comment]
I have added a pdm+1 based on the comment above confirming we can merge.

**Review by mtruj013 — APPROVED** [review]
Thanks @petesfrench !

**Pull request merged**
