### PR TITLE
feat: /gcp rebranding

### PR DESCRIPTION
**Pull request by britneywwc**
## Done

- Apply rebranding for /gcp

## QA

- Go to https://ubuntu-com-14303.demos.haus/gcp
- Check redesign against [Figma](https://www.figma.com/design/vz3yAG1nYI7r5gc3SpTUOw/24.10-ubuntu.com%2Fgcp-(Google-Cloud)?node-id=53-1836&node-type=frame&t=S7rOdhg9essH1CBn-0)
- Check that content matches with [copy doc](https://docs.google.com/document/d/1Gvt9tNFDZkqkBcP0k79C6ueTJCmNZvwoXQoU19WEa8E/edit)
- Remember to check on medium and small screens

## Issue / Card

Fixes [WD-12851](https://warthogs.atlassian.net/browse/WD-12851)

## Screenshots

[If relevant, please include a screenshot.]

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

[WD-12851]: https://warthogs.atlassian.net/browse/WD-12851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by britneywwc** [comment]
There is a lack of spacing between hr and buttons that will be addressed once updated to the latest Vanilla before the cloud bubble refresh is released.

**Comment by akbarkz** [comment]
@britneywwc please use the copy doc (and attach it to the description as well), there are some changes that should be reflected in the rebranded page.

**Comment by akbarkz** [comment]
@britneywwc please make these cards of the same height
Screenshot 2024-09-18 at 11 50 19

**Comment by juanruitina** [comment]
Logo doesn't seem to be the correct one, @mattea-turic can you assist?

Please add some space between the cards when they are stacked so we avoid this:

Screenshot 2024-09-18 at 10 43 42

I just noticed the links under "Get Ubuntu Pro on Google Cloud" don't point anywhere, not even in production (!), so I've [asked](https://docs.google.com/document/d/1Gvt9tNFDZkqkBcP0k79C6ueTJCmNZvwoXQoU19WEa8E/edit?disco=AAABTNXuecE) the owner to provide them.

**Comment by juanruitina** [comment]
UX+1 it as the other issues I pointed out, although unaddressed, are not UX related. Please hold to hear from owner on links and make sure to fix the logo.

**Comment by mattea-turic** [comment]
This pricing comp is allowing for vertical scrolling on desktop, and then both allow on mobile and tablet – just want to make sure this is intentional? 
Screenshot 2024-09-18 at 13 11 32

Eveyrthing else is good, and as we talked on MM, you'll be replacing the old logo in the hero section

**Comment by britneywwc** [comment]
@juanruitina The page owner only provided links for 22.04 and 20.04 LTS which I've included, the other versions still do not have links. Should I leave them as is or remove it from the section?

**Review by akbarkz — APPROVED** [review]

**Pull request merged**
