### PR TITLE
Update copy on /download/iot/intel-iot

### PR DESCRIPTION
**Pull request by petesfrench**
## Done

- Update copy on /download/iot/intel-iot based on [copydoc](https://docs.google.com/document/d/1hxKzPs6e6JQaa9tBqfZ55GAXrVnEryEWBja8HlXy-lc/edit)

## QA

- Check out the [demo](https://ubuntu-com-13049.demos.haus/) and compare against the [copydoc](https://docs.google.com/document/d/1hxKzPs6e6JQaa9tBqfZ55GAXrVnEryEWBja8HlXy-lc/edit)
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-5232

## Screenshots

[If relevant, please include a screenshot.]

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

### CODE REVIEW

**Comment by petesfrench** [comment]
@juanruitina can you take a look at the section 'Ubuntu optimised for next-gen Intel SoCs'  at medium and small screens. The table breaks into cards but part of the heading is not readable. Would it make sense to allow the cards to take more space to make the full heading visible?
image

**Review by anthonydillon — APPROVED** [review]
LGTM :+1:

**Comment by juanruitina** [comment]
> @juanruitina can you take a look at the section 'Ubuntu optimised for next-gen Intel SoCs' at medium and small screens. The table breaks into cards but part of the heading is not readable. Would it make sense to allow the cards to take more space to make the full heading visible?

I'd change the style to `white-space: normal` so headers wrap and take as many lines as needed; I don't see any good reason why they shouldn't take more than one line.

**Comment by petesfrench** [comment]
@juanruitina I have updated the class globally so all p-card like this behave the same way. I have also made an issue on vanilla where you input would be appreciated: https://github.com/canonical/vanilla-framework/issues/4845
Finally, can you add a ux+1 if you are happy please

**Pull request merged**
