### PR TITLE
WD-13873 - add banner for form submission

### PR DESCRIPTION
**Pull request by lizzochek**
## Done

Added a banner for form submission. Banner text agreed with UX
REMOVE FORM FROM /AWS BEFORE MERGE

## QA
- Check that the banner is correctly added and can be used for form submission

## Issue / Card
[WD-13873](https://warthogs.atlassian.net/browse/WD-13873)

[WD-13873]: https://warthogs.atlassian.net/browse/WD-13873?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by petesfrench** [comment]
I would advice you combine this with [this work](https://github.com/canonical/ubuntu.com/pull/14222). It has been hanging for a while and I don't have time to work on it right now

**Comment by lizzochek** [comment]
Screenshot 2024-09-25 at 20 13 24

**Comment by petesfrench** [comment]
It is still going above the secondary navigation
image

**Comment by lizzochek** [comment]
I’ll check if I can add it here quickly. If not, it should stay within the scope of its original task

**Comment by lizzochek** [comment]
That is not happening on my browser. I think this should be handled in a separate task
Screenshot 2024-09-26 at 11 58 46

**Comment by britneywwc** [comment]
The contact modal is not being invoked, tested on https://ubuntu-com-14339.demos.haus/azure#get-in-touch. I also don't see any form submission banner on https://ubuntu-com-14339.demos.haus/azure#contact-success.

**Comment by lizzochek** [comment]
@britneywwc that should be contact-form-success, the banner appears correctly on there. let me check the modal issue

**Comment by britneywwc** [comment]
Thanks, can you please update the QA instructions in the PR description? 

As per the form banner it is still appearing on top of the navigation for me (tested on Chrome). I'm aware that this should be handled in a separate task but just wanted to confirm that I'm seeing the same thing as Pete.

**Comment by lizzochek** [comment]
@britneywwc I fixed form submission for dynamic forms. I also added a form template on /aws#get-in-touch for you to test id it submits fine, azure one should also work correctly now

**Comment by britneywwc** [comment]
On https://ubuntu-com-14339.demos.haus/aws#get-in-touch in the mobile phone fieldset, it's showing duplicates
Screenshot 2024-09-27 at 5 42 30 PM

**Comment by britneywwc** [comment]
The payload on submission for https://ubuntu-com-14339.demos.haus/aws#get-in-touch has "how-many-machines-do-you-have", I believe this field should be concatenated in "Comments_from_lead_C". Perhaps this and the duplicated mobile phone is out of scope for this PR and should be addressed in the other form template PR. Let me know what you think.

Screenshot 2024-09-27 at 5 44 19 PM

**Comment by britneywwc** [comment]
I'm getting an error on form submission for both forms
Screenshot 2024-09-27 at 6 16 16 PM

**Comment by britneywwc** [comment]
On /aws#get-in-touch, form submission leads me to https://ubuntu-com-14339.demos.haus/thank-you?referrer=https://ubuntu-com-14339.demos.haus/aws which does not show the contact banner. If I go on https://ubuntu-com-14339.demos.haus/aws#contact-form-success the banner shows as expected.

I'll +1 this for now and you can make the changes if necessary, please remember to also remove comments before merging.

**Review by britneywwc — APPROVED** [review]

**Comment by lizzochek** [comment]
@britneywwc this can be changed by adding the return url to the form container, that's fine for now as it will be removed before merge

**Pull request merged**
