### PR TITLE
Add CVEs about page

### PR DESCRIPTION
**Pull request by britneywwc**
## Done

- Continuation from this PR https://github.com/canonical/ubuntu.com/pull/14019 due to incorrect branching
- This branch extends from the feature branch
- Added CVEs about page
- Refactored `/security/cve` to `/security/cves` and run djlint formatting on all affected files

## QA

- Go to https://ubuntu-com-14042.demos.haus//security/cves/about
- Check that design and details adheres to Figma and copy docs
- Check that side nav works
  - It should jump to heading on select
  - When scrolling through headings, the side nav links will update automatically

## Issue / Card

Fixes [WD-11852](https://warthogs.atlassian.net/browse/WD-11852)

## Screenshots

[If relevant, please include a screenshot.]

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

[WD-11852]: https://warthogs.atlassian.net/browse/WD-11852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by britneywwc** [comment]
@mtruj013 I've created a new PR that extends & merges into the feature branch.
This PR addresses the [previous comments](https://github.com/canonical/ubuntu.com/pull/14019#pullrequestreview-2159031699) brought forward from the previous PR.


Outstanding question brought forward from previous PR:
- Status icons: [comment](https://github.com/canonical/ubuntu.com/pull/14019#discussion_r1665862457)

**Review by mtruj013 — CHANGES_REQUESTED** [review]
Thanks for making the changes @britneywwc! Looks like that main cve page is throwing 500 after the changes. Thought it was an outage but prod is loading fine. Could you check? Also, the alignment here still needs fixing I think. Not sure where you and @juanruitina landed on the source of truth for the icons, but the icon-less statuses look better left aligned as in the figma IMO

figma: 
Screenshot from 2024-07-08 19-01-52
vs demo:
Screenshot from 2024-07-08 19-00-44

**Comment by britneywwc** [comment]
Thanks @mtruj013! I've aligned the icons and updated the "Ignored" status icon based on Juan's input.

**Review by mtruj013 — APPROVED** [review]
LGTM!

**Pull request merged**
