### PR TITLE
WD-10911 Update Openstack chart

### PR DESCRIPTION
**Pull request by carkod**
## Done

Update openstack chart on https://ubuntu.com/about/release-cycle#openstack-release-cycle

I don't see any comments in the spreadsheets, so will need to rely on an experienced reviewer to know if these changes are correct.

## QA

- Go to  https://ubuntu-com-13843.demos.haus/about/release-cycle#openstack-release-cycle
- Click on the Openstack tab
- and check the chart has the parts removed according to the [Jira ticket](https://warthogs.atlassian.net/browse/WD-10911?atlOrigin=eyJpIjoiNWJjMGNmN2VlNWFlNDQ2YThhZjkyOGZjMzJlYmNlZjIiLCJwIjoiaiJ9)

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-10911?atlOrigin=eyJpIjoiNWJjMGNmN2VlNWFlNDQ2YThhZjkyOGZjMzJlYmNlZjIiLCJwIjoiaiJ9

### CODE REVIEW

**Comment by petesfrench** [comment]
you need to remove them from the table also

**Comment by petesfrench** [comment]
a little out of scope, but could you make the table scrollable. It is unreadable on small screens:
image

**Comment by carkod** [comment]
@petesfrench all done

**Review by petesfrench — APPROVED** [review]
LGTM

**Pull request merged**
