### PR TITLE
[copy update] WD-4596 add download datasheet button

### PR DESCRIPTION
**Pull request by pedoch**
## Done

- Add download datasheet button

## QA

- Check out the [demo here](https://ubuntu-com-13013.demos.haus/data/mongodb) and compare it with the update requested in the [copy doc](https://docs.google.com/document/d/1_JuxbWsqTeQRRmSL0sCpM3alabr06WX4Cb-tt1BBW_I/edit).
    - Be sure to test on mobile, tablet and desktop screen sizes

## Issue / Card

- [WD-4596](https://warthogs.atlassian.net/browse/WD-4596)

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

[WD-4596]: https://warthogs.atlassian.net/browse/WD-4596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by pedoch** [comment]
@sophie-32 @carkod please take a look when you can.

**Review by carkod — APPROVED** [review]
LGTM. Can you add the link to the copy doc?

**Comment by Sophie-32** [comment]
Realize is wasn't clear in the copydoc, can we change to green button?

**Comment by Sophie-32** [comment]
And [Dowload the datasheet] should be [Download the datasheet] :)

**Comment by pedoch** [comment]
@Sophie-32 the updates have been made. Please take another look. I don't know how I missed the spelling error 🤦

**Pull request merged**
