### PR TITLE
Build an example case study using macros

### PR DESCRIPTION
**Pull request by britneywwc**
## Done

- Build an example case study using macros
- Figma design of example case study - [link](https://www.figma.com/design/AeIJ3GsqnJCHtiBYhkTuTV/24.10-Case-study-template?node-id=57-1642&t=sUGdvJIWpE4J9LMw-0)

## QA

- Go to https://ubuntu-com-14160.demos.haus/case-studies/example
- Check that the example case study matches the Figma design 25/75

## Issue / Card

Fixes [WD-14051](https://warthogs.atlassian.net/browse/WD-14051)

## Screenshots

[If relevant, please include a screenshot.]

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

[WD-14051]: https://warthogs.atlassian.net/browse/WD-14051?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by juanruitina** [comment]
- [ ] Breadcrumbs at the top are missing.
- [ ] Hide the hero description for now.
- [ ] Some accessibility tweaks: Make "Highlights" an H2 (but keep formatting), make "Contact us" at the bottom a regular paragraph (but keep formatting).
- [ ] Please tweak the last two bullet points under "Highlights" to match [the existing case study](https://pages.ubuntu.com/rs/066-EOV-335/images/European%20Space%20Agency%20Case%20Study%20April%202024%20.pdf) (my bad)
- [ ] Make turn the image copyright info block into a `small` element, so it's sized properly, but also for better semantics. It should probably be both image and copyright in a figure element for better semantics (I quite like [this approach](https://stackoverflow.com/a/21489636)), but I leave that to you.
- [ ] There's something odd with the images. The first one doesn't take 100% of the width of the main container, and it should. The other two do take 100%, but lack some spacing between them and the copyright info. Can you check what's going on?
- [ ] The contact us link should be aligned to the fourth column as per the design.

I also replied to [your comment on Figma](https://www.figma.com/design/AeIJ3GsqnJCHtiBYhkTuTV?node-id=57-1642#905992989).

One comment on the implementation in code: will we be able to add some formatting within the text with the current templates (for instance, links, italics...)?

**Comment by mattea-turic** [comment]
@britneywwc I left some comments in the [figma](https://www.figma.com/design/AeIJ3GsqnJCHtiBYhkTuTV/24.10-Case-study-template?node-id=0-1&t=WLyBqXTmHdG63cSY-1)

**Comment by britneywwc** [comment]
> * [ ]  Breadcrumbs at the top are missing.
Is there a template for content writers to control what the breadcrumbs title would be?

**Comment by juanruitina** [comment]
> Is there a template for content writers to control what the breadcrumb title would be? 

Just added it to the [template metadata](https://docs.google.com/document/d/1MuZz2rXLAZPTzc9CepW3aNbBh4cvr1r0Z-ACK5kWy-4/edit), it should be the company name 👌🏻 As for the styling, use [this component](https://vanillaframework.io/docs/patterns/breadcrumbs), same implementation as [here](https://canonical.com/careers/support-engineering).

> The contact us link should be aligned to the fourth column as per the design.

Aligned to the fourth, I just tweaked it.

**Comment by britneywwc** [comment]
This is ready for you guys, please have another look!

@juanruitina Per your comment for the figures & captions, I applied your suggestion for using `<small>` but wrapping it in a `<figure>` element ruins the image container styles so I will leave it out for now.

**Comment by juanruitina** [comment]
One minor thing: logo alt shouldn't say "logo", as per the [content guidelines](https://docs.google.com/document/d/12nLPp3ktElJCNl_i3q5fGOjWMPhPXXFsIJGH-AuxduQ/edit#heading=h.lt9pegldiqs4). You could also use the company name you used for the breadcrumbs, so "European Space Agency" instead 🤷🏻‍♂️ +1ing this already as it's minor.

Spacing between sections seems huge on desktop, but I defer to visual (@mattea-turic) on the decision there. It's looking cute 💫

**Comment by britneywwc** [comment]
Thanks for all the reviews! I made a minor tweak to the image section by adding `p-image-container--cinematic` after seeing's Lyubo's [comment](https://www.figma.com/design/AeIJ3GsqnJCHtiBYhkTuTV?node-id=57-1642&m=dev#861155742)  and that is causing the bottom two images to have some big spacing between the image and the caption. I think this is because the original image is not in the cinematic ratio, so maybe this is something to be fixed on assets? (@mattea-turic)

**Pull request merged**
