### PR TITLE
Add developer-chart.js to build.js

### PR DESCRIPTION
**Pull request by minkyngkm**
## Done

- Add `developer-chart.js` to `build.js`
- Update `src` to `dist`
- Update chart design based on [Figma](https://www.figma.com/file/fgJL13EviuGQQqx1Rl4mOd/Data-visualisation-Working-group?node-id=560%3A3024)
## QA
1. Go to  https://ubuntu-com-12071.demos.haus/desktop/developers
2. Check these two charts display
image

### CODE REVIEW

**Comment by petesfrench** [comment]
I wonder if we want to have UX/design take a look to try and get more distinction between the two graphs

**Comment by minkyngkm** [comment]
Hi @spencerbygraves could you take a look these two charts please ? 🙂

**Comment by lyubomir-popov** [comment]
hi @minkyngkm  here's the dataviz guide we worked on with Marina and Anso, there's a few differences in how the labels are presented. |Can we get closer to it?

**Comment by sowasred2012** [comment]
@minkyngkm @lyubomir-popov this close to the launch, I think let's go with what is there now and create an issue to update the look of the charts.

**Pull request closed without merging**
