### PR TITLE
[WD-4668] update kernel chart and improve charts in general

### PR DESCRIPTION
**Pull request by akbarkz**
## Done

- Updated data for Kernel chart according to [this doc](https://docs.google.com/spreadsheets/d/1jeCbxjtvg6xGsYfOrTvhtTKc2LWx-sa3DrZ5B6McExI/edit#gid=0)
- Added title to Y axis ticks for Kernel chart and shortened its  Y ticks labels according to above mentioned doc
- Added horizontal tick lines to charts for better visibility
- Put legend at the top of the chart
- Removed unnecessary setTimeout from createChart function that was messing with rendering the chart

## QA

- Navigate to /about/release-cycle#ubuntu-kernel-release-cycle and check the Kernel chart
    - Check its data on small screens when it becomes a table
- Navigate to /kernel/lifecycle and check data on Kernel charts there too, it should have same changes as on /about-release-cycle#ubuntu-kernel-release-cycle except the "Coming soon" part
- Check all other charts at the following paths if they look good and don't have any UI/non-UI bugs:
    - /about
    - /about/release-cycle#ubuntu
    - /about/release-cycle#openstack-release-cycle
    - /about/release-cycle#canonical-kubernetes-release-cycle
    - /16-04
    - /server
    - /desktop/developers (doesn't have tick lines)

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-4668

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

### CODE REVIEW

**Comment by Sophie-32** [comment]
1. put the "Interim release standard security maintenance (9 months)" part of the legend at the bottom. So purple, orange, gray.
2. Is it possible to align right the legend? (I know you said this might not work)
3. Put '23.10' in bold (since the others are labelled LTS, don't need to highlight the non LTS in any way)

I'm double checking the data which will take me a little bit longer, but these are the small fixes I found.

**Comment by Sophie-32** [comment]
1. Since can't align legend right, return it to below the chart.
2. checked the data, all looks good!

I'll plus one after the legend change.

**Comment by akbarkz** [comment]
Thanks @Sophie-32 for the review!
1. I put the legend back to the bottom of the chart.
2. I also put the Interim release legend item below so that it goes last.
3. Unfortunately, I cannot "unbold" the 23.10 label, because it's a generic behavior for all other charts as well. You can have a look at other tabs charts (OpenStack, Ubuntu), they have more non-LTS releases there and there it kind of makes sense.

**Review by carkod — APPROVED** [review]
Not sure what to compare to, I can't see all the different separations of graphs in the spreadsheet. But the views of the graph look ok.

**Pull request merged**
