### PR TITLE
WD-4878 - Clickable diagram on the Nvidia page

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done

- Added a link around the image as requested in the [copy doc](https://docs.google.com/document/d/1DJ1FuEswAojPNSX9JCLcWJwy-va5VMzuuLGwSNM0lRY/edit?disco=AAAA0iU6AU0)

## QA

- Open the demo
- Go to /nvidia
- Scroll to the "Turnkey AI solutions for the enterprise powered by Canonical and NVIDIA" and check the image is clickable as requested in the copydoc
- Check for a11y issues

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-4878

### CODE REVIEW

**Comment by albertkol** [comment]
Demo link: https://ubuntu-com-13014.demos.haus/

**Review by albertkol — APPROVED** [review]
:+1: Blissful!

**Comment by albertkol** [comment]
I am not sure what A11y checks need to be done, but code and QA is fine.

**Comment by anthonydillon** [comment]
I have confirmed we have no a11y errors via Wave:
image

**Pull request merged**
