### PR TITLE
/download/server 24.04 updates

### PR DESCRIPTION
**Pull request by mtruj013**
## Done

- Updated copy as per [doc](https://docs.google.com/document/d/1Qob4Ni_y1ffIdSWqaw2xH0dxiHZQmkRGP5nuoBhIfyM/edit)
- Drive bys:
  - Updated previous lts versions on releases.yaml and added server iso sizes 

## QA

- View the site locally in your web browser at: http://0.0.0.0:8001/download/server
    - Be sure to test on mobile, tablet and desktop screen sizes
- See that the requested changes have been made

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-10052

### CODE REVIEW

**Review by lizzochek — APPROVED** [review]
I see some extra spaces before section tags, please check the formatting

**Comment by mtruj013** [comment]
Thanks @lizzochek , linting is passing both in the gh check and locally. According to our djlint configuration having an empty line in between sections seems to be allowed. If you can point to any documentation that suggests this should not be the case please let me know and I'll use that convention moving forward

**Comment by juanruitina** [comment]
- [ ] Update the link to the release notes: https://discourse.ubuntu.com/t/noble-numbat-release-notes/39890
- [ ] Minor visual feedback: the HR under Alternative downloads and Alternative architectures seem to have excessive spacing below. Adding the `p-rule` class to those HRs seems to do the trick.

**Comment by mtruj013** [comment]
@juanruitina ready!

**Comment by juanruitina** [comment]
LGTM!

**Pull request merged**
