### PR TITLE
Exclude the lang-kr from the blog listing

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done

- Exclude the lang-kr from the blog listing

## QA

- Visit the /blog listing and see there are no Korean posts
- Visit [production](https://ubuntu.com/blog) and see that there is

### CODE REVIEW

**Review by minkyngkm — APPROVED** [review]
LGTM no KR post 👍 test-python checks is failing though..

**Comment by andesol** [comment]
Not in /blog, but I still see this on the main page 

image

(which links to a 404)

**Review by edlerd — APPROVED** [review]
LGTM

**Comment by anthonydillon** [comment]
Come on test :runner:

**Pull request merged**
