### PR TITLE
WIP Final Meganav

### PR DESCRIPTION
**Pull request by sowasred2012**
## Done

Demo: https://ubuntu-com-12252.demos.haus/

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

Fixes #

## Screenshots

[If relevant, please include a screenshot.]

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

### CODE REVIEW

**Comment by carkod** [comment]
I believe this cypress check fail is correct? at least for the ` navigation_spec.js` it might be worth running locally and fixing it once you're done with the work.

**Comment by carkod** [comment]
@anthonydillon any idea where we at with this?

**Comment by anthonydillon** [comment]
That's why I updated the global nav project. Not sure, will check it.

**Comment by lyubomir-popov** [comment]
A few visual glitches in the way the logo is displayed [here](https://www.figma.com/file/BSP7FqnRMcMvO7kCozJKUa/Ubuntu.com-navigation-update-Iteration-9?type=design&node-id=5818%3A29043&t=zmqPKoJvRemgQAGY-1):

- The CoF is 2px smaller than in the official logo. Because of that, it doesn't align vertically with the baseline of the wordmark, and leaves more space at the bottom of the tag than in the official logo
- The tag is about 2px narrower

cc @marcushas

**Comment by anthonydillon** [comment]
@petesfrench are you working from this branch?

**Pull request closed without merging**
