### PR TITLE
feat: Create /pricing/contact-us

### PR DESCRIPTION
**Pull request by petesfrench**
## Done

- Create a contact-us form, this uses the default form template

## QA

- Check [the form](https://ubuntu-com-14387.demos.haus/pricing/contact-us) submits and goes to the same place as the other pricing contact us forms

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-15540 

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

### CODE REVIEW

**Comment by petesfrench** [comment]
@eliman11

**Comment by juanruitina** [comment]
Understanding this is just adding a standard form for the pricing page, this looks good to me.

[Thank you page](https://ubuntu-com-14387.demos.haus/pricing/thank-you) is not rebranded yet, maybe worth addressing @lyubomir-popov? I see it being the case for other forms such as the main one: https://ubuntu.com/contact-us/form/thank-you

**Review by anthonydillon — CHANGES_REQUESTED** [review]
There a several broken aria labels on the forms. At a glance it looks like `aria-labelledby="desktop/workstation"` is trying to target `id="desktop-workstation"` which mismatching.

**Comment by petesfrench** [comment]
@anthonydillon This was a good catch that affecting a lot of different forms, thanks. Can you take another look please?

**Review by anthonydillon — APPROVED** [review]
Nice work and thanks for the extra fix. Code and QA :+1:

**Pull request merged**
