### PR TITLE
Semi-done Checkout redesign

### PR DESCRIPTION
**Pull request by ClementChaumel**
## Done

- Turned the modal into a checkout "page"
- got rid of the duplicated buy button component

## QA

- go to https://ubuntu-com-12013.demos.haus/advantage
- make a logged in UA purchase
- make a logged in Blender purchase
- make a logged in Offer purchase
- make a logged out UA purchase
- make a logged out Blender purchase

## Missing

- Free trial
- Renewals

### CODE REVIEW

**Comment by albertkol** [comment]
Initial feedback:

- [ ] VAT is not immediately calculated on country/VAT number input (details for the endpoint: https://github.com/canonical/ubuntu.com/pull/11687)
- [ ] Step 3 is not in edit on page load for guest user:
image
- [ ] scrolling in the checkout overlay is a bit weird; also it covers the menu, not sure if it's intended @wgx ?
- state of the form is not storing the input; also refreshing the page takes me back to product selection, not sure if it's intended @wgx ?
- [ ] I recommend moving the captcha field at the end of the from, getting any errors de-selects the captcha and you have re-check it every time @wgx thoughts?
- [ ] as a guest with an UO account after signing in I am taken back to the product selector rather than checkout
- [ ] we had intentions to move to this endpoint for the purchase (details: https://github.com/canonical/ubuntu.com/pull/11367) which can be used for shop, renewals and offer purchases; additionally it ensures user accounts (if missing) and updates account info; but I suppose that can be achieved as a separate step
- [ ] renewal purchase overlay is weirdly positioned
image

**Comment by albertkol** [comment]
- [ ] scrolling in the checkout overlay is a bit weird; also it covers the menu, not sure if it's intended?
- [ ] title of the checkout says Ubuntu Advantage
- [ ] Adding the VAT does immediately update the price of the purchase. Removing it does not decrease it again. Even if I switch to a non-VAT country same behaviour.
- [ ] Confirm and buy is missing the new checkbox added by Min last week
- [ ] Scrolling hides the checkout
- [ ] guest trial purchase fails. it seems to not pass any products data with the response
- [ ] logged in trial purchase fails. it seems to not pass any products data with the response
- [ ] Do we no longer store the state of the checkout anymore? Including status that it's open/closed and the data stored inside?
- [ ] Success redirect is to /pro/dashboard

**Comment by ClementChaumel** [comment]
Can't reproduce the VAT behaviour you're describing @albertkol

**Comment by albertkol** [comment]
Docs with issues I find from the QA: 
https://docs.google.com/document/d/1uCC1Q-vSb6j3FfNjNgzO7zqquQgtHvT1zu6gzIIbSBc/edit#

**Pull request merged**
