### PR TITLE
1.26+ck1 docs changes

### PR DESCRIPTION
**Pull request by evilnick**
## Done

- Release notes for 1.26+ck1
- changes for vsphere integrator/provider
- link updates

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes

### CODE REVIEW

**Comment by carkod** [comment]
Can you squash one of the `fix-lint` commits? or maybe even better rebase them into the `1.26+ck1-release`?

**Review by carkod — APPROVED** [review]
LGTM

**Comment by evilnick** [comment]
@carkod done, I think

**Comment by evilnick** [comment]
Feel free to merge and publish whenever - I don't have permissions to do that

**Pull request merged**
