### PR TITLE
WIP- Pro selector

### PR DESCRIPTION
**Pull request by ClementChaumel**
## Done

- Update the Feature and support section to match the designs

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
- [List additional steps to QA the new features or prove the bug has been resolved]

### CODE REVIEW

**Comment by wgx** [comment]
@ClementChaumel please remove Oracle from public clouds - we hoped it would be ready, but it's not yet ready.

**Comment by wgx** [comment]
@ClementChaumel 
image

22.04 needs a little "Coming soon" chip as shown above ^^

**Comment by wgx** [comment]
@ClementChaumel Typo in footer, swap `annualy` for `annually`

**Comment by wgx** [comment]
@ClementChaumel 

Weird non-happy path:

1. Choose physical
2. Choose "infra only"
3. Change to desktop
4. "infra only" becomes greyed out AND selected

Should:

Auto-select "Pro" AND grey out "infra only".

**Comment by ClementChaumel** [comment]
> @ClementChaumel image
> 
> 22.04 needs a little "Coming soon" chip as shown above ^^

@wgx do you know which Vanilla component it is supposed to be? The closest I can find is the [chip](https://vanillaframework.io/docs/patterns/chip) but I'm afraid it's a bit too big

**Comment by wgx** [comment]
@ClementChaumel when a free trial is available, show the 'free trial' dense chip in the sticky summary bar at the bottom

**Comment by frankban** [comment]
I collected some minor issues found while QAing at the end of https://docs.google.com/document/d/1XMoQBO8O4aPQIA9GC3KAlTCGITbRJJR5MEliSrY1Hbo/edit

**Comment by lyubomir-popov** [comment]
@ClementChaumel QA here - https://www.figma.com/file/ZAihKxF2wmj9wvoPSnPKmY/Commercial%3A-UA-%2Fsubscribe?node-id=1526%3A12194

**Pull request merged**
