### PR TITLE
refactor: Rebrand /pricing/thank-you

### PR DESCRIPTION
**Pull request by petesfrench**
## Done

- Rebase /pricing/thank-you based on [figma design](https://www.figma.com/design/vxxQijDub9nQrU3ZAYcXri/Pricing?node-id=0-1&node-type=canvas&t=zWIbN8ZHdZbmYrFX-0)

## QA

- Check [the demo](https://ubuntu-com-14347.demos.haus/) matches the design
- Check page is navigable with keyboard

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-12870

### CODE REVIEW

**Comment by petesfrench** [comment]
@mattea-turic hold off reviewing this please

**Comment by petesfrench** [comment]
@mattea-turic Can you take a look at this please?

**Comment by mattea-turic** [comment]
for consistency, do you think you could replicate the thank you page hero that's been done on e.g. [aws/thank-you](https://ubuntu.com/aws/thank-you):
Screenshot 2024-09-30 at 11 01 54

Image [here](https://assets.ubuntu.com/v1/b0fa63e9-christina-wocintechchat-com-LQ1t-8Ms5PY-unsplash.png)

**Comment by petesfrench** [comment]
@mattea-turic I have applied your suggested changes, can you take another look please

**Comment by petesfrench** [comment]
@samhotep you are the lucky winner of the smallest PR to review!

**Review by samhotep — APPROVED** [review]
LGTM!

**Pull request merged**
