### PR TITLE
Get Ubuntu meganav section

### PR DESCRIPTION
**Pull request by sowasred2012**
## Done

- Added Get Ubuntu section to meganav

## QA

- Visit https://ubuntu-com-12221.demos.haus/
- On desktop, click "Get Ubuntu" in the navigation menu (this is the only nav section this PR covers, anything else is being tackled in other PRs)
  - Check that the links work
- View on mobile, see that you can navigate to "Get Ubuntu" via the Menu CTA and interact with all the links
- See that the content matches the design: https://www.figma.com/file/BSP7FqnRMcMvO7kCozJKUa/Ubuntu.com-navigation-update-Iteration-9?node-id=4872%3A27351

## Issue / Card

Fixes https://github.com/canonical/web-squad/issues/5984

### CODE REVIEW

**Comment by lyubomir-popov** [comment]
- too much space under button
image


-misalignement
image


 
image
image
image
image

**Comment by lyubomir-popov** [comment]
Thaks @sowasred2012 looks grea,t just a couple of niggles:
make height of submenu items match their parent height  
make download button to the right when there is space

**Comment by bartaz** [comment]
Seems that opening "All Canonical" menu doesn't close other menus in the nav

meganav

**Comment by bartaz** [comment]
All Canonical seems to have broken arrow icon when it is in top nav

image


And BTW, it took me a while to discover that there is a hidden navigation on the bubble pages… And probably I only found it because I knew it may be hidden on top :/
It's really confusing when you navigate somewhere and navigation completely changes. I was clicking "back" to get to previous page and open meganav again.

**Comment by sowasred2012** [comment]
> Seems that opening "All Canonical" menu doesn't close other menus in the nav
> 
> meganav [ meganav ](https://user-images.githubusercontent.com/83575/198603089-ae4aafa4-093f-4d26-8262-1b2a97b424dd.gif) [ ](https://user-images.githubusercontent.com/83575/198603089-ae4aafa4-093f-4d26-8262-1b2a97b424dd.gif)

@bartaz yep - I am collating issues with global nav in a separate issue, this PR is just for the Get Ubuntu section (and is going into a feature branch)

**Comment by sowasred2012** [comment]
> All Canonical seems to have broken arrow icon when it is in top nav
> 
> image
> 
> And BTW, it took me a while to discover that there is a hidden navigation on the bubble pages… And probably I only found it because I knew it may be hidden on top :/ It's really confusing when you navigate somewhere and navigation completely changes. I was clicking "back" to get to previous page and open meganav again.

This is another one of the issues I'll be addressing in another PR - but yep, I totally agree about the bubble nav... when the feature branch is ready I'll reach out to the wider team for a big QA/thoughts on that.

**Comment by bartaz** [comment]
There is kindof nested hover in Ubuntu Desktop section - when you can click on whole section and button in it.
It's confusing, and probably breaks some accessibiilty guidelines. Is this supposed to link to the same place?

If we want to have both click targets, maybe the hover effect should still be active on whole section when button is hovered.

double-hover

**Comment by sowasred2012** [comment]
> There is kindof nested hover in Ubuntu Desktop section - when you can click on whole section and button in it. It's confusing, and probably breaks some accessibiilty guidelines. Is this supposed to link to the same place?
> 
> If we want to have both click targets, maybe the hover effect should still be active on whole section when button is hovered.
> 
> double-hover [ double-hover ](https://user-images.githubusercontent.com/83575/198608127-49f72967-b7d1-4531-b75b-41eef2df383e.gif) [ ](https://user-images.githubusercontent.com/83575/198608127-49f72967-b7d1-4531-b75b-41eef2df383e.gif)

Agree, concerns were raised about this with @lyubomir-popov and @cassiocassio - previously that CTA was positioned in the footer of the dropdown, but research found that users didn't find it easily, so this is being trialled as an improvement. I've updated the hover state, it is meant that there are two links "Ubuntu Desktop" and the LTS CTA.

**Comment by bartaz** [comment]
> I've updated the hover state, it is meant that there are two links "Ubuntu Desktop" and the LTS CTA.

It would be clearer, if the top 2 lines (Ubuntu Desktop, Free OS) and the button under it would be completely separate click areas. Let top have the hover like other section, and button should be outside of it. It is really not clear that they are 2 separate link to 2 different locations.

**Comment by cassiocassio** [comment]
> 

They point to different places - the text teaches you about the desktop , the green button immediatley starts the download. The mousever should reflect two distinct choices. I will gather some quick "what do you think happens when you click this" feedback, to confirm user expectations.

**Comment by lyubomir-popov** [comment]
@sowasred2012 the desktop version looks fine, a few things for the mobile version:

- resizing makes the inner sections "wobble" left and right
- we jump to a linear version way too soon, the blue links can be on the side instead of under until we hit the 622 breakpoint:
- 
image
As previously discussed, all levels of the nav should slide left/right on mobile, not just the leaf nodes:
image


all of the above are improvements and I am fine if this gets merged as is, then we iterate.

**Comment by petesfrench** [comment]
Not related to this PR but I will flag anyway, the link `s390x` under `servers`, takes you to the correct url, but there is zero mention of `s390x` on the page.

**Comment by sowasred2012** [comment]
@petesfrench I've updated the KVM link, and added the medium screen issue to https://github.com/canonical/web-squad/issues/6178 (it's out of scope for this PR)

**Review by petesfrench — APPROVED** [review]

**Pull request merged**
