### PR TITLE
[WD-6255] /desktop/developers copy update

### PR DESCRIPTION
**Pull request by akbarkz**
## Done

- Add changes according to [copy doc](https://docs.google.com/document/d/1VJ3xT2ViC-CvL0UmsAUzpYFmvpuqUP4AbpnlPm8tqOA/edit)
- Add more space for the chart on the page
   - On large screens designated 7 columns of the grid instead of 6 as before. This means that the text content on the left now has 5 columns. 
   - On smaller screens remove centering utility classes so that now the chart takes the full width without any spacings from the sides.

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
- Navigate to /desktop/developers page and check changes there

## Issue / Card

Closes https://warthogs.atlassian.net/browse/WD-6255

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

### CODE REVIEW

**Comment by lyubomir-popov** [comment]
@akbarkz I think this section is trying to do too much. How about breaking it up into two, so the chart can be full width?

**Comment by akbarkz** [comment]
> @akbarkz I think this section is trying to do too much. How about breaking it up into two, so the chart can be full width?

@lyubomir-popov since on large screens there is also an image on top of the chart, how to split this section into two is not obvious. I might need your help with designing it. But considering the urgency (since this is a part of 23.10 release) can we go with this implementation and revisit the design afterwards? Wdyt?

**Comment by lyubomir-popov** [comment]
50/50 split, drop the image

**Comment by lyubomir-popov** [comment]
yes if irgent release as is but please make an issue to late update it.

**Comment by juanruitina** [comment]
> 50/50 split, drop the image

I agree with Lyubo, this seems a good fix. Changes are good UX-wise, so +1ing it.

**Comment by akbarkz** [comment]
> yes if irgent release as is but please make an issue to late update it.

Splitting 50/50 is the way it was implemented already and when you squeeze the screen to a minimum large resolution you can notice that X ticks interlap with each other. Therefore since it's still not clear how to implement it the right way, I suggest we address this issue in another ticket that I created under the same epic: https://warthogs.atlassian.net/browse/WD-6657

**Comment by lyubomir-popov** [comment]
@akbarkz what I meant was this:
image


code: 
```
  <div class="u-fixed-width">
    <h2>Why choose Ubuntu for Desktop?</h2>
  </div>
  <div class="row">
    <div class="col-6">
      <h3 data-gtm-vis-recent-on-screen1014405_499="219" data-gtm-vis-first-on-screen1014405_499="219" data-gtm-vis-total-visible-time1014405_499="100" data-gtm-vis-has-fired1014405_499="1">The developers’ choice</h3>
      
      
    </div>
    <div class="col-6">
      <ul class="p-list">
        <li class="p-list__item is-ticked">Using Ubuntu Desktop provides a common platform for development, test, and
          production environments.
        </li>
        <li class="p-list__item is-ticked">Tools, such as <a href="https://juju.is/">Juju</a>, <a href="https://microk8s.io/">Microk8s</a>, and <a href="https://multipass.run/">Multipass</a> make
          developing, testing, and cross-building easy and affordable.
        </li>
        <li class="p-list__item is-ticked"><strong>Long term support (LTS)</strong> releases are delivered every
          2-years, with 5 years of standard support extended to 10 years with an Ubuntu Pro Desktop subscription.
        </li>
        <li class="p-list__item is-ticked">New Developer editions of Ubuntu Desktop are released every 6-months, with
          9-months of support and access to the latest kernel, libraries, and new upstream OS features.</li>
      </ul><p data-gtm-vis-has-fired1014405_503="1">
        <a href="/about/release-cycle">The Ubuntu release cycle&nbsp;›</a>
      </p>
      
      
    </div>
  </div><div class="row p-strip--light is-shallow ">
    
    <div class="col-12 ">
      
      <div class="u-hide--small" id="server-desktop-eol"><svg class="chart" width="1386" height="292"><g class="gantt-chart" width="1386" height="292" transform="translate(189, 0)"><rect class=" chart__bar--orange" y="0" transform="translate(57.8104038329911,222)" height="12" width="289.36878850102676"></rect><rect class=" chart__bar--orange" y="0" transform="translate(173.58959616700892,193)" height="12" width="289.36878850102664"></rect><rect class=" chart__bar--charcoal" y="0" transform="translate(173.58959616700892,181)" height="12" width="578.5791923340178"></rect><rect class=" chart__bar--orange" y="0" transform="translate(289.2104038329911,164)" height="12" width="289.36878850102664"></rect><rect class=" chart__bar--charcoal" y="0" transform="translate(289.2104038329911,152)" height="12" width="578.5791923340178"></rect><rect class=" chart__bar--aubergine" y="0" transform="translate(347.17919233401784,222)" height="12" width="289.3687885010266"></rect><rect class=" chart__bar--orange" y="0" transform="translate(404.9895961670089,135)" height="12" width="289.36878850102676"></rect><rect class=" chart__bar--charcoal" y="0" transform="translate(404.9895961670089,123)" height="12" width="578.5791923340179"></rect><rect class=" chart__bar--aubergine" y="0" transform="translate(462.9583846680356,193)" height="12" width="289.2104038329911"></rect><rect class=" chart__bar--orange" y="0" transform="translate(520.6104038329911,106)" height="12" width="289.2104038329911"></rect><rect class=" chart__bar--charcoal" y="0" transform="translate(520.6104038329911,94)" height="12" width="578.5791923340178"></rect><rect class=" chart__bar--grey" y="0" transform="translate(552.6041067761806,77)" height="12" width="43.2390143737166"></rect><rect class=" chart__bar--aubergine" y="0" transform="translate(578.5791923340178,164)" height="12" width="289.2104038329911"></rect><rect class=" chart__bar--grey" y="0" transform="translate(581.4301163586584,48)" height="12" width="43.562383070956"></rect><rect class=" chart__bar--grey" y="0" transform="translate(610.4145106091719,19)" height="12" width="43.397399041752124"></rect><rect class=" chart__bar--aubergine" y="0" transform="translate(694.3583846680357,135)" height="12" width="289.2104038329911"></rect><rect class=" chart__bar--aubergine" y="0" transform="translate(809.8208076659822,106)" height="12" width="289.36878850102664"></rect><g class="x axis" transform="translate(0, 252)" fill="none" font-size="10" font-family="sans-serif" text-anchor="middle"><g class="tick" opacity="1" transform="translate(43.56238307095597,0)"><line stroke="currentColor" y2="6" y1="-272"></line><text fill="currentColor" y="9" dy="0.71em">2014</text></g><g class="tick" opacity="1" transform="translate(159.18319073693817,0)"><line stroke="currentColor" y2="6" y1="-272"></line><text fill="currentColor" y="9" dy="0.71em">2016</text></g><g class="tick" opacity="1" transform="translate(274.962383070956,0)"><line stroke="currentColor" y2="6" y1="-272"></line><text fill="currentColor" y="9" dy="0.71em">2018</text></g><g class="tick" opacity="1" transform="translate(390.58319073693815,0)"><line stroke="currentColor" y2="6" y1="-272"></line><text fill="currentColor" y="9" dy="0.71em">2020</text></g><g class="tick" opacity="1" transform="translate(506.36238307095596,0)"><line stroke="currentColor" y2="6" y1="-272"></line><text fill="currentColor" y="9" dy="0.71em">2022</text></g><g class="tick" opacity="1" transform="translate(621.9831907369382,0)"><line stroke="currentColor" y2="6" y1="-272"></line><text fill="currentColor" y="9" dy="0.71em">2024</text></g><g class="tick" opacity="1" transform="translate(737.7623830709559,0)"><line stroke="currentColor" y2="6" y1="-272"></line><text fill="currentColor" y="9" dy="0.71em">2026</text></g><g class="tick" opacity="1" transform="translate(853.3831907369382,0)"><line stroke="currentColor" y2="6" y1="-272"></line><text fill="currentColor" y="9" dy="0.71em">2028</text></g><g class="tick" opacity="1" transform="translate(969.1623830709559,0)"><line stroke="currentColor" y2="6" y1="-272"></line><text fill="currentColor" y="9" dy="0.71em">2030</text></g><g class="tick" opacity="1" transform="translate(1084.7831907369382,0)"><line stroke="currentColor" y2="6" y1="-272"></line><text fill="currentColor" y="9" dy="0.71em">2032</text></g></g><g class="y axis" fill="none" font-size="10" font-family="sans-serif" text-anchor="start"><g class="tick" opacity="1" transform="translate(0,25)"><line stroke="currentColor" x2="0"></line><text fill="currentColor" x="-189" dy="0.32em">23.10 (Mantic Minotaur)</text></g><g class="tick" opacity="1" transform="translate(0,54)"><line stroke="currentColor" x2="0"></line><text fill="currentColor" x="-189" dy="0.32em">23.04 (Lunar Lobster)</text></g><g class="tick" opacity="1" transform="translate(0,83)"><line stroke="currentColor" x2="0"></line><text fill="currentColor" x="-189" dy="0.32em">22.10 (Kinetic Kudu)</text></g><g class="tick" opacity="1" transform="translate(0,112)"><line stroke="currentColor" x2="0"></line><text fill="currentColor" x="-189" dy="0.32em" class="chart__label--bold">22.04 LTS (Jammy Jellyfish)</text></g><g class="tick" opacity="1" transform="translate(0,141)"><line stroke="currentColor" x2="0"></line><text fill="currentColor" x="-189" dy="0.32em" class="chart__label--bold">20.04 LTS (Focal Fossa)</text></g><g class="tick" opacity="1" transform="translate(0,170)"><line stroke="currentColor" x2="0"></line><text fill="currentColor" x="-189" dy="0.32em" class="chart__label--bold">18.04 LTS (Bionic Beaver)</text></g><g class="tick" opacity="1" transform="translate(0,199)"><line stroke="currentColor" x2="0"></line><text fill="currentColor" x="-189" dy="0.32em" class="chart__label--bold">16.04 LTS (Xenial Xerus)</text></g><g class="tick" opacity="1" transform="translate(0,228)"><line stroke="currentColor" x2="0"></line><text fill="currentColor" x="-189" dy="0.32em" class="chart__label--bold">14.04 LTS (Trusty Tahr)</text></g></g></g></svg><svg class="chart-key" width="550" height="96"><g class="chart-key__row" transform="translate(0, 0)" height="24"><rect class="chart__bar--orange" width="18" height="14" y="0"></rect><text class="chart-key__label" x="24" y="13">LTS standard security maintenance for Ubuntu Main (initial 5 years)</text></g><g class="chart-key__row" transform="translate(0, 21)" height="24"><rect class="chart__bar--aubergine" width="18" height="14" y="0"></rect><text class="chart-key__label" x="24" y="13">LTS Expanded Security Maintenance (ESM) for Ubuntu Main (additional 5 years)</text></g><g class="chart-key__row" transform="translate(0, 42)" height="24"><rect class="chart__bar--charcoal" width="18" height="14" y="0"></rect><text class="chart-key__label" x="24" y="13">LTS Expanded Security Maintenance (ESM) for Ubuntu Universe (10 years)</text></g><g class="chart-key__row" transform="translate(0, 63)" height="24"><rect class="chart__bar--grey" width="18" height="14" y="0"></rect><text class="chart-key__label" x="24" y="13">Interim release standard security maintenance (9 months)</text></g></svg></div>
      <table class="u-hide--medium u-hide--large">
        <thead>
          <tr>
            <td>&nbsp;</td>
            <th scope="col">Released</th>
            <th scope="col">End of Standard Support</th>
            <th scope="col">End of Life</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><strong>14.04 LTS (Trusty Tahr)</strong></td>
            <td>Apr&nbsp;2014</td>
            <td>Apr&nbsp;2019</td>
            <td>Apr&nbsp;2024</td>
          </tr>
          <tr>
            <td><strong>16.04 LTS (Xenial Xerus)</strong></td>
            <td>Apr&nbsp;2016</td>
            <td>Apr&nbsp;2021</td>
            <td>Apr&nbsp;2026</td>
          </tr>
          <tr>
            <td><strong>18.04 LTS (Bionic Beaver)</strong></td>
            <td>Apr&nbsp;2018</td>
            <td>Apr&nbsp;2023</td>
            <td>Apr&nbsp;2028</td>
          </tr>
          <tr>
            <td><strong>20.04 LTS (Focal Fossa)</strong></td>
            <td>Apr&nbsp;2020</td>
            <td>Apr&nbsp;2025</td>
            <td>Apr&nbsp;2030</td>
          </tr>
          <tr>
            <td><strong>22.04 LTS (Jammy Jellyfish)</strong></td>
            <td>Apr&nbsp;2022</td>
            <td>Apr&nbsp;2027</td>
            <td>Apr&nbsp;2032</td>
          </tr>
          <tr>
            <td>22.10 (Kinetic Kudu)</td>
            <td>Oct&nbsp;2022</td>
            <td>Jul&nbsp;2023</td>
          </tr>
          <tr>
            <td>23.04 (Lunar Lobster)</td>
            <td>Apr&nbsp;2023</td>
            <td>Jan&nbsp;2024</td>
          </tr>
          <tr>
            <td>23.10 (Mantic Minotaur)</td>
            <td>Oct&nbsp;2023</td>
            <td>Jul&nbsp;2024</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="u-fixed-width">
    <hr class="p-separator">
  </div>
  <div class="row">
    <div class="col-6 u-vertically-center">
      <div class="p-logo-section">
        <div class="p-logo-section__items">
          <div class="p-logo-section__item u-align--center" style="padding:25px">
            
<div class=" lazyloaded" data-noscript="">
    <img src="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_288,h_288/https://assets.ubuntu.com/v1/1d1d6362-AI_sml.svg" srcset="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_576,h_576/https://assets.ubuntu.com/v1/1d1d6362-AI_sml.svg 2x" alt="" width="288" height="288" loading="lazy">
  </div>

          </div>
          <div class="p-logo-section__item ">
            
<div class=" lazyloaded" data-noscript="">
    <img src="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_288,h_288/https://assets.ubuntu.com/v1/1bc694f0-nvidia-cuda-logo.png" srcset="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_576,h_576/https://assets.ubuntu.com/v1/1bc694f0-nvidia-cuda-logo.png 2x" alt="" width="288" height="288" loading="lazy" class="p-logo-section__logo">
  </div>

          </div>
          <div class="p-logo-section__item ">
            
<div class=" lazyloaded" data-noscript="">
    <img src="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_288,h_288/https://assets.ubuntu.com/v1/eea32cc5-jupyter-logo.png" srcset="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_576,h_576/https://assets.ubuntu.com/v1/eea32cc5-jupyter-logo.png 2x" alt="" width="288" height="288" loading="lazy" class="p-logo-section__logo">
  </div>

          </div>
          <div class="p-logo-section__item ">
            
<div class=" lazyloaded" data-noscript="">
    <img src="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_288,h_288/https://assets.ubuntu.com/v1/462ef9f5-keras-logo.png" srcset="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_576,h_576/https://assets.ubuntu.com/v1/462ef9f5-keras-logo.png 2x" alt="" width="288" height="288" loading="lazy" class="p-logo-section__logo">
  </div>

          </div>
          <div class="p-logo-section__item">
            
<div class=" lazyloaded" data-noscript="">
    <img src="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_288,h_288/https://assets.ubuntu.com/v1/c1fd7abe-scikit-learn-logo.png" srcset="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_576,h_576/https://assets.ubuntu.com/v1/c1fd7abe-scikit-learn-logo.png 2x" alt="" width="288" height="288" loading="lazy" class="p-logo-section__logo">
  </div>

          </div>
          <div class="p-logo-section__item">
            
<div class=" lazyloaded" data-noscript="">
    <img src="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_145,h_145/https://assets.ubuntu.com/v1/57dd2115-TensorFlow-logo.svg" srcset="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_290,h_290/https://assets.ubuntu.com/v1/57dd2115-TensorFlow-logo.svg 2x" alt="" width="145" height="145" loading="lazy" class="p-logo-section__logo">
  </div>

          </div>
          <div class="p-logo-section__item">
            
<div class=" lazyloaded" data-noscript="">
    <img src="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_288,h_288/https://assets.ubuntu.com/v1/f41c87c6-pytorch-logo.png" srcset="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_576,h_576/https://assets.ubuntu.com/v1/f41c87c6-pytorch-logo.png 2x" alt="" width="288" height="288" loading="lazy" class="p-logo-section__logo">
  </div>

          </div>
        </div>
      </div>
    </div>
    <div class="col-6">
      <h2>Access to cutting-edge hardware and software</h2>
      <ul class="p-list">
        <li class="p-list__item is-ticked">Ubuntu ships with the latest toolchains for Python, Rust, Ruby, Go, PHP and
          Perl, and users get first access to the latest updates for key libraries and packages.</li>
        <li class="p-list__item is-ticked">Ubuntu is the OS of choice for data science and machine learning, with
          support for popular frameworks like <a href="https://opencv.org/">OpenCV</a>, <a href="https://www.tensorflow.org/">TensorFlow</a>, <a href="https://keras.io/">Keras</a>, <a href="https://pytorch.org/">PyTorch</a> and <a href="https://www.kubeflow.org/">Kubeflow</a>.</li>
        <li class="p-list__item is-ticked">Ubuntu is the target platform for the <a href="https://github.com/NVIDIA/data-science-stack">NVIDIA data science stack</a>, which enables GPU
          accelerated data science workloads to be run locally before deploying to the cloud.</li>
      </ul>
      <p data-gtm-vis-has-fired1014405_503="1">
        <a href="/ai">How Ubuntu enables AI innovation&nbsp;›</a>
      </p>
    </div>
  </div>
  <div class="u-fixed-width">
    <hr class="p-separator">
  </div>
  <div class="row">
    <div class="col-8">
      <h3 data-gtm-vis-has-fired1014405_499="1">A rich ecosystem</h3>
      <ul class="p-list">
        <li class="p-list__item is-ticked">With a <a href="https://snapcraft.io/store">Snap Store</a> of over 7,000
          applications in addition to the Ubuntu repository, it’s easy to tailor Ubuntu desktop to your needs.</li>
        <li class="p-list__item is-ticked">Development tools include Visual Studio Code, IntelliJ, GitKraken, Unity and
          Blender.</li>
        <li class="p-list__item is-ticked">Office productivity tools include Slack, Microsoft Teams, Dropbox, and Zoom
          as well as the Microsoft-compatible LibreOffice.</li>
        <li class="p-list__item is-ticked">Media, gaming, and content creation apps include Spotify, Steam, Discord and
          OBS Studio.</li>
      </ul>
      <p data-gtm-vis-has-fired1014405_503="1">
        <a href="https://snapcraft.io">Learn more about Snapcraft&nbsp;›</a>
      </p>
    </div>
  </div>
  <div class="u-fixed-width">
    <div class="p-logo-section">
      <div class="p-logo-section__items">
        <div class="p-logo-section__item ">
          
<div class=" lazyloaded" data-noscript="">
    <img src="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_288,h_288/https://assets.ubuntu.com/v1/a8d0ab5b-slack-logo.png" srcset="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_576,h_576/https://assets.ubuntu.com/v1/a8d0ab5b-slack-logo.png 2x" alt="" width="288" height="288" loading="lazy" class="p-logo-section__logo">
  </div>

        </div>
        <div class="p-logo-section__item ">
          
<div class=" lazyloaded" data-noscript="">
    <img src="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_288,h_288/https://assets.ubuntu.com/v1/e850e108-dropbox-logo.png" srcset="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_576,h_576/https://assets.ubuntu.com/v1/e850e108-dropbox-logo.png 2x" alt="" width="288" height="288" loading="lazy" class="p-logo-section__logo">
  </div>

        </div>
        <div class="p-logo-section__item ">
          
<div class=" lazyloaded" data-noscript="">
    <img src="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_288,h_288/https://assets.ubuntu.com/v1/df56b8a5-libreoffice-logo.png" srcset="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_576,h_576/https://assets.ubuntu.com/v1/df56b8a5-libreoffice-logo.png 2x" alt="" width="288" height="288" loading="lazy" class="p-logo-section__logo">
  </div>

        </div>
        <div class="p-logo-section__item ">
          
<div class=" lazyloaded" data-noscript="">
    <img src="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_288,h_288/https://assets.ubuntu.com/v1/c7dae67a-zoom-logo.png" srcset="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_576,h_576/https://assets.ubuntu.com/v1/c7dae67a-zoom-logo.png 2x" alt="" width="288" height="288" loading="lazy" class="p-logo-section__logo">
  </div>

        </div>
        <div class="p-logo-section__item ">
          
<div class=" lazyloaded" data-noscript="">
    <img src="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_288,h_288/https://assets.ubuntu.com/v1/2abedabb-google-chrome-logo.png" srcset="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_576,h_576/https://assets.ubuntu.com/v1/2abedabb-google-chrome-logo.png 2x" alt="" width="288" height="288" loading="lazy" class="p-logo-section__logo">
  </div>

        </div>
        <div class="p-logo-section__item ">
          
<div class=" lazyloaded" data-noscript="">
    <img src="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_288,h_288/https://assets.ubuntu.com/v1/60c97798-unity-logo.png" srcset="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_576,h_576/https://assets.ubuntu.com/v1/60c97798-unity-logo.png 2x" alt="" width="288" height="288" loading="lazy" class="p-logo-section__logo">
  </div>

        </div>
        <div class="p-logo-section__item ">
          
<div class=" lazyloaded" data-noscript="">
    <img src="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_288,h_288/https://assets.ubuntu.com/v1/b8c1f574-intellij-logo.png" srcset="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_576,h_576/https://assets.ubuntu.com/v1/b8c1f574-intellij-logo.png 2x" alt="" width="288" height="288" loading="lazy" class="p-logo-section__logo">
  </div>

        </div>
        <div class="p-logo-section__item ">
          
<div class=" lazyloaded" data-noscript="">
    <img src="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_288,h_288/https://assets.ubuntu.com/v1/3294f6e8-vs-code-logo.png" srcset="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_576,h_576/https://assets.ubuntu.com/v1/3294f6e8-vs-code-logo.png 2x" alt="" width="288" height="288" loading="lazy" class="p-logo-section__logo">
  </div>

        </div>
        <div class="p-logo-section__item ">
          
<div class=" lazyloaded" data-noscript="">
    <img src="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_288,h_288/https://assets.ubuntu.com/v1/982a200a-blender-notext-logo.png" srcset="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_576,h_576/https://assets.ubuntu.com/v1/982a200a-blender-notext-logo.png 2x" alt="" width="288" height="288" loading="lazy" class="p-logo-section__logo">
  </div>

        </div>
        <div class="p-logo-section__item ">
          
<div class=" lazyloaded" data-noscript="">
    <img src="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_288,h_288/https://assets.ubuntu.com/v1/aa55fac4-microsoft-teams-logo.png" srcset="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_576,h_576/https://assets.ubuntu.com/v1/aa55fac4-microsoft-teams-logo.png 2x" alt="" width="288" height="288" loading="lazy" class="p-logo-section__logo">
  </div>

        </div>
      </div>
    </div>
  </div>
  <div class="u-fixed-width">
    <hr class="p-separator">
  </div>
  <div class="row">
    <div class="col-6">
      <div class="p-logo-section">
        <div class="p-logo-section__items">
          <div class="p-logo-section__item">
            
<div class="lazyload" data-noscript="">
  <noscript>
    <img
      src="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_288,h_288/https://assets.ubuntu.com/v1/11814428-hp-logo.png"
      srcset="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_576,h_576/https://assets.ubuntu.com/v1/11814428-hp-logo.png 2x"
      alt="Hewlett Packard"
      width="288"
      height="288"
      loading="lazy"
      class="p-logo-section__logo"
    />
  </noscript>
</div>

          </div>
          <div class="p-logo-section__item">
            
<div class="lazyload" data-noscript="">
  <noscript>
    <img
      src="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_288,h_288/https://assets.ubuntu.com/v1/c70b529e-lenovo-logo.png"
      srcset="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_576,h_576/https://assets.ubuntu.com/v1/c70b529e-lenovo-logo.png 2x"
      alt="Lenovo"
      width="288"
      height="288"
      loading="lazy"
      class="p-logo-section__logo"
    />
  </noscript>
</div>

          </div>
          <div class="p-logo-section__item">
            
<div class="lazyload" data-noscript="">
  <noscript>
    <img
      src="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_288,h_288/https://assets.ubuntu.com/v1/987acdaa-dell-logo.png"
      srcset="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_576,h_576/https://assets.ubuntu.com/v1/987acdaa-dell-logo.png 2x"
      alt="Dell"
      width="288"
      height="288"
      loading="lazy"
      class="p-logo-section__logo"
    />
  </noscript>
</div>

          </div>
          <div class="p-logo-section__item">
            
<div class="lazyload" data-noscript="">
  <noscript>
    <img
      src="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_288,h_288/https://assets.ubuntu.com/v1/6079d02b-amd-logo.png"
      srcset="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_576,h_576/https://assets.ubuntu.com/v1/6079d02b-amd-logo.png 2x"
      alt="AMD"
      width="288"
      height="288"
      loading="lazy"
      class="p-logo-section__logo"
    />
  </noscript>
</div>

          </div>
          <div class="p-logo-section__item">
            
<div class="lazyload" data-noscript="">
  <noscript>
    <img
      src="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_288,h_288/https://assets.ubuntu.com/v1/67f81bfe-intel-new-logo.png"
      srcset="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_576,h_576/https://assets.ubuntu.com/v1/67f81bfe-intel-new-logo.png 2x"
      alt="Intel"
      width="288"
      height="288"
      loading="lazy"
      class="p-logo-section__logo"
    />
  </noscript>
</div>

          </div>
          <div class="p-logo-section__item">
            
<div class="lazyload" data-noscript="">
  <noscript>
    <img
      src="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_288,h_288/https://assets.ubuntu.com/v1/711be910-arm-logo.png"
      srcset="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_576,h_576/https://assets.ubuntu.com/v1/711be910-arm-logo.png 2x"
      alt="ARM"
      width="288"
      height="288"
      loading="lazy"
      class="p-logo-section__logo"
    />
  </noscript>
</div>

          </div>
          <div class="p-logo-section__item">
            
<div class="lazyload" data-noscript="">
  <noscript>
    <img
      src="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_288,h_288/https://assets.ubuntu.com/v1/cd765ccc-nvidia-logo.png"
      srcset="https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_576,h_576/https://assets.ubuntu.com/v1/cd765ccc-nvidia-logo.png 2x"
      alt="Nvidia"
      width="288"
      height="288"
      loading="lazy"
      class="p-logo-section__logo"
    />
  </noscript>
</div>

          </div>
        </div>
      </div>
    </div>
    <div class="col-6">
      <h3 data-gtm-vis-has-fired1014405_499="1">Certified hardware</h3>
      <ul class="p-list">
        <li class="p-list__item is-ticked">Streamline deployment of Ubuntu Desktop with <a href="/certified">certified
            hardware</a> from OEMs including Dell, Lenovo, and HP — no additional configuration required.</li>
        <li class="p-list__item is-ticked">Ubuntu performs out of the box across a wide range of laptops, desktops, and
          workstations, including the HP Z series and Dell XPS and Precision lines.</li>
        <li class="p-list__item is-ticked"><a href="/desktop/partners">Strategic partnerships</a> extend to component
          manufacturers and Ubuntu is certified to work with the full range of NVIDIA GPUs.</li>
      </ul>
      <p data-gtm-vis-has-fired1014405_503="1">
        <a href="/certified">Ubuntu certified hardware&nbsp;›</a>
      </p>
    </div>
  </div>
```

**Review by Dampolo03 — APPROVED** [review]
👍

**Pull request merged**
