### PR TITLE
Build /healthcare vertical page

### PR DESCRIPTION
**Pull request by petesfrench**
## Done

**BLOCKED: until we have a new marketing manager, see conversation in [issue](https://warthogs.atlassian.net/browse/WD-2046?atlOrigin=eyJpIjoiZDU3YjZiZWM5NDI4NDE0MzljZTgzYzk4NzI3OTYzNzEiLCJwIjoiaiJ9)**
**BLOCKED: waiting on forms/ids**

- Build /healthcare vertical page based off of [the copydoc](https://docs.google.com/document/d/1ty83VsGznwHCNI1nnoLKEVhP3mByZSeCO80yb-iLc8o/edit#) and using the [brochure guide](https://vanillaframework.io/docs/layouts/brochure)

## QA

- Go to https://ubuntu-com-12753.demos.haus/healthcare and check that it matches the content in [the copydoc](https://docs.google.com/document/d/1ty83VsGznwHCNI1nnoLKEVhP3mByZSeCO80yb-iLc8o/edit#) and using the [brochure guide](https://vanillaframework.io/docs/layouts/brochure)

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-3043

### CODE REVIEW

**Comment by petesfrench** [comment]
Hey @lyubomir-popov, so I had a go building this page with the new brochure guide. For me it was still very unclear which layout is best to use in this situation.

**Comment by lyubomir-popov** [comment]
@petesfrench you've gotten very close, let's pair up tomorrow to iron out a few small things. Great to see you using the guide!

**Comment by anthonydillon** [comment]
@juanruitina could you review and suggest a good way to integrate this new page into the site, please? There is currently no navigation to it.

**Comment by juanruitina** [comment]
I think the most natural place to put this is in the meganav > Enterprise > Sectors. Our offering on this vertical looks similar to that of Government (certification, compliance), so I'd place the link right after Government.

Screenshot 2023-04-05 at 10 22 32

**Comment by anthonydillon** [comment]
Maybe also the footer? What about cross referencing is related page content?

**Comment by juanruitina** [comment]
Sure, please add it to the footer too.

As for cross referencing, we don't seem to have much related content. [Content on the blog](https://ubuntu.com/blog/tag/healthcare) is over a decade old; we mention healthcare under [HPC](https://ubuntu.com/hpc/use-cases), but we don't cover HPC in this page. Some fresh blog post would be good.

Off scope, but couldn't help noticing: I see some inconsistencies between meganav and footer for sectors:

* Industrial is only on the footer.
* Signage and Gateways are only on the meganav.
* Organisations and Robotics are elsewhere on the footer, not under Sectors.

Is this intentional? I think at least "Industrial" should be under sectors in the meganav (Signage and Gateways are under IoT anyway).

**Comment by petesfrench** [comment]
@egezeytun Do you think we can close this? It is quite outdated and I don't see any movement on it

**Comment by egezeytun** [comment]
Hi Pete,

Yes please close it. I didn't realize we had a PR. I don't see any movement
on this coming our way soon anyway.

Bets,

**Comment by petesfrench** [comment]
Closing as per conversation above

**Pull request closed without merging**
