### PR TITLE
Make select boxes with on change affects accessible

### PR DESCRIPTION
**Pull request by petesfrench**
## Done

**This script can be added to other sites documentation pages when it is merged**
- When a select input has an 'onchange' listener attached to it, browsing the options using a keyboard will trigger the listener before the user can confirm their selection. this PR implements JS to allow the onchange function to work as normally but also allow people using keyboard navigation to browse the options and use the 'enter' or 'tab' key to confirm their option.
- This addresses the accessibility issues listed in [this document](https://github.com/canonical/ubuntu.com/files/10708064/select.lists.cannot.be.operated.from.the.keyboard.if.they.have.an.onchange.handler.that.performs.navigation.because.the.handler.fires.as.the.user.moves.the.selection.up.and.down.using.the.keyboard.ods)

## QA

- Go to one of the links listed in the document above, for example https://ubuntu-com-12528.demos.haus/security/certifications/docs/fips-faq (they all use the same template, so testing a couple will surfice)
- Navigate to the version select input using your keyboard, once the select is in focus their are two way you can select an option: 
  1. click enter to expand the dropdown, use your arrow keys to navigate to your desired option and click enter or tab. You should see the page reload to the correct version.
  2. Using the arrow keys change the option (with the dropdown still closed), when you have found your desired option click enter. You should see the page reload to the correct version.
- The page should not reload unless you have confirmed a choice with enter or tab.
- Next, try selecting an option using just the mouse and ensure that works as expected.
- Finally, it is advised to go through the keyboard method with your screen reader on the ensure what is read is appropriate and logical.

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-1567

### CODE REVIEW

**Review by pedoch — APPROVED** [review]
LGTM! Just a thought, wouldn't using the `id` be better for specificity.

I was able to test it with my keyboard and mouse. Both methods work. But I wasn't able to get the screen reader to come on in my browser so I couldn't test that part. Also, the demo isn't running, I don't know why but I had to run it locally.

**Comment by petesfrench** [comment]
@pedoch good catch, I have updated it accordingly

**Comment by pedoch** [comment]
Hey @petesfrench should this still be tested with a screen reader? Cos other than that everything looks good

**Comment by mtruj013** [comment]
On Mac, this is the behavior:

https://user-images.githubusercontent.com/17607612/219046701-bdb20156-a825-440f-b2d6-97486fdefe2d.mov


Selecting an option on the dropdown doesn't refresh the page even after moving the focus away from the element. Once the screen reader is closed it also blocks the interaction with the dropdown altogether in that once you try to open the dropdown (so once you click the chevron) it'll just refresh the page instead of opening the menu.

**Comment by petesfrench** [comment]
@mtruj013 can you take another look at this please

**Comment by mtruj013** [comment]
@petesfrench it's still not letting me select a different version via the dropdown (without the screen reader). With the screen reader the page only reloads once I move the focus from the dropdown, but I think that's minor compared to the first issue

**Comment by petesfrench** [comment]
@mtruj013 can you give this one another try please

**Comment by mtruj013** [comment]
Sorry @petesfrench this is still not working. When the screen reader is off, clicking the dropdown automatically refreshes the page and blocks me from making a selection. With the screenreader I can use the dropdown as normal, it just won't refresh until I remove focus from the dropdown.

**Comment by petesfrench** [comment]
@mtruj013 The behavior you are describing when navigating with the keyboard (the screen reader being on shouldn't make a difference) is the expected behavior, so that's good! However, you should still be able to make a selection using the mouse. Let's jump in a call and pair on this, as it is very difficult for me to debug without having a mac.

**Review by mtruj013 — APPROVED** [review]
Not been this hype to approve a pr in a while 😆 LGTM!

**Pull request merged**
