### PR TITLE
Rebrand /server

### PR DESCRIPTION
**Pull request by petesfrench**
*Please review [/server/hyperscale](https://github.com/canonical/ubuntu.com/pull/13521) first*

## Done

- Refreshes /server based on [design](https://www.figma.com/file/Kw2SwMkH49tN54NbnKs5dt/24.04-U.com---server-(rebranding)?node-id=0%3A1&mode=dev) and [copydoc](https://docs.google.com/document/d/1vxLhtbjgPs9PCNEhr7fbhEoErCPMXYFfU4UTKH7Kbq4/edit) changes
- Moves the footer into a template
- Fly by: Adds some spaces to style.scss

## QA

- Go to [the demo]()
- Check that it matches the [design](https://www.figma.com/file/Kw2SwMkH49tN54NbnKs5dt/24.04-U.com---server-(rebranding)?node-id=0%3A1&mode=dev) and the [copydoc](https://docs.google.com/document/d/1vxLhtbjgPs9PCNEhr7fbhEoErCPMXYFfU4UTKH7Kbq4/edit)
- Check the page on large, medium and small screens
- Check the code abides by [vanilla](https://vanillaframework.io/) best practices

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-8325

### CODE REVIEW

**Comment by petesfrench** [comment]
@lyubomir-popov @juanruitina please leave review comments here. i made a mistake with git and merged the other branch prematurely. I have applied any changes that were already commented

**Comment by juanruitina** [comment]
Just two minor comments:

- [ ] Visual feedback: above the logo clouds, I see there's not the usual (small) space between the separator and the heading and link. The `u-no-padding--top` class seems to be the culprit.
- [ ] Can you place the Juju, MAAS and LXD logos inside H3 tags? That way we end up with a nice heading tree (with the logos' alt text as their content).

+1ing this already.

**Comment by juanruitina** [comment]
One more thing: there's a small typo under Ubuntu Pro: "maintanance"

**Review by lizzochek — APPROVED** [review]
LGTM!

**Pull request merged**
