### PR TITLE
twitter to x icon

### LINKED ISSUE #13246: Request to Update Twitter Icon to X
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary
The Twitter logo has been updated recently and hasn't been updated on the site.

## Process
Steps to Reproduce
Step 1: Go to footer section and see twitter old lcon

## Current and expected result
Current Behavior - Old twitter icon
Screenshot 2023-10-14 at 4 29 06 PM

Expected Behavior
The Twitter logo should be changed to X.
Screenshot 2023-10-14 at 4 29 01 PM

[Describe what happened and what you expected.]

## Screenshot

[If relevant, please include a screenshot.]

## Browser details

[Please tell us what browser(s) you used when you encountered this bug and any other information that might be relevant, like if you block javascript, run an ad blocker, etc...]

### PR DESCRIPTION
**Pull request by sarthak-kumar-shailendra**
## Done

Changed the svg of twitter icon to x

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: https://ubuntu-com-13247.demos.haus/
    - Be sure to test on mobile, tablet and desktop screen sizes
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

Fixes #13246 , https://warthogs.atlassian.net/browse/WD-6905

## Screenshots

Screenshot 2023-10-14 at 4 29 01 PM

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

### CODE REVIEW

**Comment by sarthak-kumar-shailendra** [comment]
@mtruj013 can you pls check this?

**Comment by lyubomir-popov** [comment]
Hi can you please define the height in rems not pixels? 
On smaller screens, everything looks fine:
image
But on screens larger than 1680px, where we [increase the value of 1rem](https://github.com/canonical/vanilla-framework/blob/82975b9dd91d3654b2e60424fed13a1acf1fe54a/scss/_base_typography.scss#L24), things get misaligned for two of the icons:
image

Bonus points for fixing the 4th icon as well :)

**Comment by sarthak-kumar-shailendra** [comment]
@lyubomir-popov Have converted pixels to rems and fixed the fourth icon as well. Can you check again?

**Comment by lyubomir-popov** [comment]
hi, thanks for doing this - but there's still something keeping it smaller @sarthak-kumar-shailendra:

image

maybe it is the 32px height on the svg itself? Can you please compare how the two in the middle (the bigger ones) are built?

**Comment by sarthak-kumar-shailendra** [comment]
This is how it's looking for screen having width 1698px in local. Are we checking the latest changes?

Screenshot 2023-10-17 at 4 05 28 PM

**Comment by lyubomir-popov** [comment]
I believe I'm looking at the latest demo - just opened it in a different browser with cleared cache, they still seem different heights:
image

**Comment by sarthak-kumar-shailendra** [comment]
is my last commit published in the latest demo?
I am asking because even I was getting 2 larger icons in local when height was mentioned in px (for larger screens) but after changing it to rem there's no spacing issue for both smaller and larger screens.
@lyubomir-popov @mtruj013

**Comment by mtruj013** [comment]
@lyubomir-popov @sarthak-kumar-shailendra looks like new pushes aren't triggering demo builds if they come from external contributors. I've manually triggered a build, it should be up to date now (same link)

**Comment by sarthak-kumar-shailendra** [comment]
@lyubomir-popov can you check now?

**Comment by lyubomir-popov** [comment]
Thanks @sarthak-kumar-shailendra the sizing is now correct, but I also noticed the X letter is transparent, and shows the background underneath. Can you please use the same colour as other icons in the set (light gray, solid). This is to ensure readability regardless of what plugins/browser features a user might have.

**Comment by sarthak-kumar-shailendra** [comment]
@lyubomir-popov  did you mean like this? 
Screenshot 2023-10-20 at 4 45 30 PM

**Comment by lyubomir-popov** [comment]
@sarthak-kumar-shailendra yes but please use the same colour as other icons in this set: #e5e5e5

**Comment by sarthak-kumar-shailendra** [comment]
@lyubomir-popov have pushed the changes, will need to trigger a new build manually

**Comment by mtruj013** [comment]
@sarthak-kumar-shailendra @lyubomir-popov demo should be up to date

**Review by mtruj013 — APPROVED** [review]
Thanks @sarthak-kumar-shailendra, LGTM!

**Pull request merged**
