### PR TITLE
WD-16842 Redirect /landscape/install to Docs

### PR DESCRIPTION
**Pull request by muhammad-ali-pk**
## Done

- Remove /landscape/install page
- Add redirection to docs

## QA

- View the site  in your web browser at: https://ubuntu-com-14582.demos.haus/landscape
- Click on the Install button in navigation
- Get redirected to /landscape/docs/quickstart-deployment

## Issue / Card

Fixes #[WD-16842](https://warthogs.atlassian.net/browse/WD-16842)

[WD-16842]: https://warthogs.atlassian.net/browse/WD-16842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by eliman11** [comment]
Thanks @muhammad-ali-pk! Would it be possible for the 'Install' tab to still be selected? At the moment if you click into 'Install' it changes the tab to show that 'Docs' is selected. 
Screenshot 2024-12-17 at 09 56 59

**Comment by muhammad-ali-pk** [comment]
@eliman11 Thanks Elaine! Done.

**Comment by eliman11** [comment]
Looks great, thanks for the quick fix!

**Review by fasih-mehmood — APPROVED** [review]
LGTM

**Pull request merged**
