### PR TITLE
perf: Merge print.scss into styles.scss to reduce the number of .css requests on page load

### PR DESCRIPTION
**Pull request by petesfrench**
## Done

- Merge print.scss into styles.scss to reduce the number of .css requests on page load
- Removes custom styling for `u-no-print` as it now [exists in vanilla](https://vanillaframework.io/docs/utilities/no-print)

## QA

- Go to https://ubuntu.com/, load the page with network and see there is a separate request for print.css.
- Attempt to print the page and see that it is formatted for printing (no nav, images adjusted etc)
- Go to https://ubuntu-com-14213.demos.haus/ load the page with network and see there is **not** a separate request for print.css.
- Attempt to print the page and see that it is formatted the same as on live

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-14184

### CODE REVIEW

**Comment by petesfrench** [comment]
@pastelcyborg I see, I have moved it down and this has made some small changes to how it is rendered. However it still doesn't match prod - I am not sure which one is correct.

It might be good to get the input of @lyubomir-popov

**Comment by lyubomir-popov** [comment]
It's difficult to give a +1 on something that looks like this. The reality is, we have don noo work whatsoever on print styles. If we want to improve them, I suggest we create a separate project for it, as it will likely require a lot of work.

FOr the time being, I suggest ensuring any code modifications do not result in visible changes, so we don't have to approve changes which are far from ideal (as is the prod version as well).

**Comment by petesfrench** [comment]
I am quite open to suggestions on this one. Including 2 imports made it very easy to define media 'screen' and 'print', this doesn't seem to be so easy within the SCSS files. So many styles are leaking through causing the differences highlighted above. We could definitely be more granular with our print styles, but this would require more work and more upkeep.  I am seriously considering taking the performance hit for the added practically it brings. Would like to here your thought here @pastelcyborg

**Comment by petesfrench** [comment]
In this case I will close this PR. Can I leave it to your to create an issue in Jira to address this?

**Pull request closed without merging**
