### PR TITLE
Added nginx proxy_pass and konf file clean up

### PR DESCRIPTION
**Pull request by jkfran**
## Done

- Added nginx proxy_pass and konf file clean up

### CODE REVIEW

**Review by nottrobin — APPROVED** [review]

**Comment by nottrobin** [comment]
LGTM. `/pro/docs/client` hangs - I guess that's expected because IS haven't opened the firewall yet? Did we remember to ask for this for the demo cluster as well?

**Comment by sowasred2012** [comment]
Adding don't merge label until the IS ticket is resolved and we know whether we need to take any more action.

**Comment by sowasred2012** [comment]
There's a meeting with IS next week (w/c 21st Nov)

**Comment by sowasred2012** [comment]
After the meeting, this solution is off the table, according to Robin. Closing.

**Pull request closed without merging**
