### PR TITLE
Landing refresh

### PR DESCRIPTION
**Pull request by mtruj013**
_Continuation of https://github.com/canonical/ubuntu.com/pull/13755_
## Done

- Applied rebrand as per [design](https://www.figma.com/file/Le4TTzyOFbcbqTPJ1tVoZT/U.com---Home-(rebranding)?node-id=0%3A1&mode=dev)

## QA

- View the site locally in your web browser at: https://ubuntu-com-13803.demos.haus/
    - Be sure to test on mobile, tablet and desktop screen sizes
- Check against design
- Check against doc and prod see that no functionality has changed 

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-8630

### CODE REVIEW

**Comment by mtruj013** [comment]
@camillet16 @lyubomir-popov I've switched to the new logos for the offending section but they still look a bit stretched :(
image

**Comment by mtruj013** [comment]
@lyubomir-popov logos should be fine now, could you please take another look?

**Comment by juanruitina** [comment]
- [ ] I see some takeovers having too much text in the subtitle, could we add some logic so they become smaller when they have more than x characters? @lyubomir-popov 

Screenshot 2024-04-26 at 16 41 32

- [ ] On smaller viewports, there are some double separators in lists

Screenshot 2024-04-26 at 16 38 05

- [ ] On smaller viewports, some lists have separators, some don't, and the result is a bit messy. This makes sense on desktop, but I feel they should all look the same on mobile/tablet.

- [ ] The dates in the blog section look wrong, should we just stack them?

Screenshot 2024-04-26 at 16 45 11

- [ ] Can we make the learn more and contact links unique via aria-labels? E.g. in the case below, "Learn more about public cloud optimisation", "Contact us about public cloud optimisation": 

Screenshot 2024-04-26 at 16 49 05

@lyubomir-popov I'd like to see how these links (Learn more, contact us) perform in a heatmap, I have a feeling they might get a bit lost in the page.

**Comment by lyubomir-popov** [comment]
new illustrations are now available - ca nwe use them please? https://assets.ubuntu.com/manager?tag=u.c-homepage-isometric-dark

**Pull request merged**
