### PR TITLE
[Sunbeam GA Launch] WD-3622 revamp `/openstack/install`

### PR DESCRIPTION
**Pull request by pedoch**
## Done

- Updated `/openstack/install` based on copy doc.

## QA

- Check out the [demo here](https://ubuntu-com-12912.demos.haus/openstack/install) and compare it with the changes on the [copy doc](https://docs.google.com/document/d/1eQ16jzv6YRGzG_k_C-tUnhM06k6_Ic6fZM-x_ARMzuc/edit).

## Issue / Card

- [WD-3622](https://warthogs.atlassian.net/browse/WD-3622)

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

[WD-3622]: https://warthogs.atlassian.net/browse/WD-3622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by juanruitina** [comment]
Nice work Ochuko, can you please make the background of the instructions transparent as well?

I see the "Single-node mode" and "Multi-node mode" H2 heading sort of clash with headings within the documentation pages:

Screenshot 2023-05-31 at 12 36 22

@tytus-kurek May I suggest that we move those headings above the lists? Something like this:

Screenshot 2023-05-31 at 12 35 39

**Comment by tytus-kurek** [comment]
@juanruitina I am happy with the change you proposed. Please note that the installation instructions are synced automatically from microstack.run/docs, so this change would need to be implemented carefully not to break the existing automation.

**Comment by juanruitina** [comment]
@tytus-kurek Sure, we'll make sure it doesn't break the automation. @pedoch Can you tweak this?

**Comment by juanruitina** [comment]
I just meant making all the page have white background, instead of the gray the current version has in the middle section.

**Review by tbille — APPROVED** [review]
Code LGTM

**Comment by juanruitina** [comment]
LGTM!

**Comment by pedoch** [comment]
@julpal7 ping!

**Comment by julpal7** [comment]
Hi @pedoch! I have a few comments, please look into them when you have a minute.

1. A period is missing at the end of the last sentence.
Screenshot 2023-06-07 at 15 17 08<br>

2. We have double padding above "take the next step", adding up to 128px and creating too much white space. Could you please try reducing it to 64px (for example by removing the bottom padding on div.p-strip)?<br>
Screenshot 2023-06-07 at 15 29 39

3. There is a responsiveness issue when scaling the page to the width of 621-830 px, the background is obstructing the text.
Screenshot 2023-06-07 at 15 57 27<br>

4. In other resolutions, the icon is creating issues as well.
Screenshot 2023-06-07 at 16 09 04<br>
Since the background seems problematic and overlaps with other elements, maybe instead of trying to work around the scaling we could replace it with another one with less prominent Surus? For example, the one used here:
Screenshot 2023-06-07 at 16 12 48

Thank you in advance for the updates!

**Comment by pedoch** [comment]
@julpal7 I've made the changes, could you take a look?

**Comment by julpal7** [comment]
@pedoch Just one last thing, could you please add more padding under the text on the header? it still overlaps with the Suru on smaller resolutions, padding under the link should solve the issue.
Screenshot 2023-06-09 at 12 31 18
That's it, everything is fine otherwise. Thank you for the updates.

**Comment by pedoch** [comment]
@julpal7 I know you're sprinting on marketplace this week but please take a look when you can. I've added some space before the suru on medium and small screens to stop the content overlay

**Comment by julpal7** [comment]
@pedoch I apologize for being so nitpicky about the scaling, but there are still some issues between 1035 - 875px of width:
Screenshot 2023-06-12 at 14 52 16
<br> It seems that with the added bottom padding, some excessive padding also appeared at the top of the header. Could you please cross-reference it against the main "OpenStack" tab, for example? Maybe it will help with the rest of responsiveness issues, those two pages have the exact same background and the main one scales properly.
Screenshot 2023-06-12 at 14 56 23
Screenshot 2023-06-12 at 14 59 10

**Comment by pedoch** [comment]
@julpal7 this install page was using a deep suru, that's why there was more space at the top. I've fixed it now so everything should be good

**Comment by pedoch** [comment]
Hi @tytus-kurek please can I get a +1 from you for this PR? It's ready to go live tomorrow. Here's the demo for your perusal: https://ubuntu-com-12912.demos.haus/openstack/install

**Comment by tytus-kurek** [comment]
@pedoch, thanks for sharing. The "Get OpenStack" button should link to the "Single-node, multi-node or large-scale cluster?" section, not the contact form. Apart from that everything LGTM.

**Comment by pedoch** [comment]
@tytus-kurek I've updated the link on the "Get OpenStack" button, can I get your +1?

**Comment by tytus-kurek** [comment]
@pedoch everything LGTM. Also look at https://github.com/canonical/ubuntu.com/pull/12950

**Comment by tytus-kurek** [comment]
@pedoch could you please rename the `Get OpenStack` button to the `Install OpenStack` button?

**Comment by pedoch** [comment]
Hi @tytus-kurek I think this may have to come as a copy update request. With the change made on the copy doc. You can also as for it to be high priority so it's picked up faster.

**Comment by tytus-kurek** [comment]
@pedoch I've just requested those changes in the copy doc.

**Pull request merged**
