### PR TITLE
Update / based on copy changes

### PR DESCRIPTION
**Pull request by petesfrench**
## Done

- Updates / based on [copy changes](https://docs.google.com/document/d/1ySJxQbqVdeH4Tra0zwBm2Tn0s56kFGnEF7d8xDRTxwU/edit#heading=h.g8inespqhurp)

## QA

- Go to https://ubuntu-com-12704.demos.haus/ and compare against [copy changes](https://docs.google.com/document/d/1ySJxQbqVdeH4Tra0zwBm2Tn0s56kFGnEF7d8xDRTxwU/edit#heading=h.g8inespqhurp)

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-2654

### CODE REVIEW

**Review by pedoch — COMMENTED** [review]
Looks good. But I saw the comment on changing the URL for the link. There doesn't seem to be any URL on the text in the change requested so I guess that's something to be resolved before I approve.

**Comment by lyubomir-popov** [comment]
@petesfrench turn it into a proper strip, with 4 columns for the illustration and 8 columns for the title?
Or drop it altogether if this is meant to be a small "ticker" element. The graphic hasn't been designed to work at small sizes so we can't keep the whole thing inobtrusive, but also with a graphic and we must choose  between the two. I would ask @lechsandecki how prominent this needs to be and chosse between the two options above based on the answer.

**Comment by lechsandecki** [comment]
Not sure I follow. It doesn't have to be very prominent. I'd need to see what you mean to help you with that.

**Comment by lechsandecki** [comment]
@leiaru-c do you want to chime-in?

**Comment by leiaru-c** [comment]
@lechsandecki already did in the copy doc!

**Comment by petesfrench** [comment]
@lyubomir-popov I tried using `col`s instead of `header-icon` to make the image larger and more visible, what do you think?
image

**Comment by lyubomir-popov** [comment]
@petesfrench I would do this:

`<section class="p-strip">
  <div class="row">
    
    <div class="col-9">
      
      <p><strong><a href="/blog/18-04-end-of-standard-support">End of standard support for 18.04 LTS - 31 May 2023</a></strong><br><a href="/blog/18-04-end-of-standard-support">Upgrade to the latest Ubuntu LTS or get extended coverage until 2028 with Ubuntu Pro</a></p>
    </div>
  </div>
</section>
<hr class="
    is-fixed-width">
`

preview:
image

**Comment by petesfrench** [comment]
@lyubomir-popov Updated

**Comment by lyubomir-popov** [comment]
Sorry last thought - @juanruitina do you think this is a valid case for a notification? Just thinking whether we can reuse an exiating component. It would look like this:


image


code (if @juanruitina agrees wih this treatment):
```
<div class="u-fixed-width">
    <div class="p-notification--information u-no-margin--bottom">
  <div class="p-notification__content">
    <h5 class="p-notification__title"><a href="/blog/18-04-end-of-standard-support">End of standard support for 18.04 LTS - 31 May 2023</a></h5>
    <p class="p-notification__message"><span href="">Upgrade to the latest Ubuntu LTS or get extended coverage until 2028 with Ubuntu Pro</span></p>
  </div>
</div>
  </div>
```

**Comment by juanruitina** [comment]
Yep, I think using the notification makes more sense, makes it immediately understandable as a notice still not too prominent.

**Comment by petesfrench** [comment]
@lyubomir-popov No worries, I think it looks a lot better! Can you take one last look please?

**Comment by lyubomir-popov** [comment]
looks good thanks @petesfrench!

**Comment by petesfrench** [comment]
@pedoch Could you take another look at this please?

**Review by pedoch — APPROVED** [review]
LGTM! 👍

**Pull request merged**
