### PR TITLE
[copy update] WD-6241 - update on `/managed`

### PR DESCRIPTION
**Pull request by pedoch**
## Done

- Update on `/managed`

## QA

- Check out [the demo here](https://ubuntu-com-13155.demos.haus/managed) and compare it with the updates requested by Rajan on [the copy doc](https://docs.google.com/document/d/19GoMudyrd9Zt1e7kfj-koL-Lt0RGYzWHRPuuKYUPvqw/edit).

## Issue / Card

- [WD-6241](https://warthogs.atlassian.net/browse/WD-6241)

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

[WD-6241]: https://warthogs.atlassian.net/browse/WD-6241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by anthonydillon — APPROVED** [review]
LGTM :+1: there are lots of other suggestions in the copy doc. Might be worth @Sophie-32 and @gloriaquintanilla to take a look?

**Comment by Sophie-32** [comment]
sorry trying to look and the demo is opening up the live page (without updates)

**Comment by pedoch** [comment]
@Sophie-32 the only thing that changes in this PR is the addition of a card in the "Learn more about Managed IT Services" section. I think @anthonydillon meant you should take a look at the copy doc, there are a ton of other suggestions from a deleted user.

**Comment by Sophie-32** [comment]
I see its already merged but the track changes in the copydoc aren't accepted. Checking if that's on purpose?

**Comment by pedoch** [comment]
@Sophie-32 my bad, I'll accept the changes now.

**Comment by pedoch** [comment]
@Sophie-32 I just checked and the suggestions left were made by a deleted user earlier in the year (February). Those changes weren't part of this PR and aren't part of what is currently live now. I think it'll be up to the PM or Gloria to decide what to do with them. Either discard them or raise another copy update to implement them.

**Comment by Sophie-32** [comment]
Understand, I'll work it out with them and make sure the copydoc gets cleaned up so its less confusing the next time.

**Pull request merged**
