### PR TITLE
Multi-cloud build

### PR DESCRIPTION
**Pull request by mtruj013**
## Done

- Built page as per [copy doc](https://docs.google.com/document/d/1ULGMyz1DoAPIDTHOBE1r3SF7hTbZRs8kZsAG8LD6qyA/edit#) and [design](https://github.com/canonical-web-and-design/ubuntu.com/issues/10502)

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: https://ubuntu-com-10570.demos.haus/telco/osm/multi-cloud
- Check against above copy doc and design and ensure all is correct
- Test buttons to make sure everything is working as expected

## Issue / Card

Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10501

## Screenshots
Screenshot 2021-10-07 at 18 30 39

### CODE REVIEW

**Comment by mtruj013** [comment]
> Hi Can we have these three headings "public cloud support", "private cloud support" and "SDN assist" one after the one instead besides each other?

@spencerbygraves Hi, please lmk how you'd like me to move forward with this style-wise. Should I just house each of these in their own rows keeping the `p-strip--light` backdrop?

**Comment by SirSamTumless** [comment]
> Hi Can we have these three headings "public cloud support", "private cloud support" and "SDN assist" one after the one instead besides each other?

@WajeehaHamid Why? We've had this page designed so it matches our other pages and creates a nice content flow?

**Comment by spencerbygraves** [comment]
>please lmk how you'd like me to move forward with this style-wise

@mtruj013 I would leave as is unless there's a particular reason to change it. Could we also use the dark background from the design in the resources section please. [You can see an example here](https://ubuntu.com/kubernetes).

Thanks.

**Comment by WajeehaHamid** [comment]
that's fine. thanks all

**Pull request merged**
