### PR TITLE
[Copy update] IoT Download Page

### PR DESCRIPTION
**Pull request by Lukewh**
## Done

- Updated copy according to https://github.com/canonical/marketplace-tribe/issues/2786

## QA

- View the demo, or checkout the branch and run `dotrun`.
- Visit /download/iot
- Check copy against the copy doc and the design against the design

## Issue / Card

Fixes https://github.com/canonical/marketplace-tribe/issues/2786

## Screenshots

image

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

### CODE REVIEW

**Comment by davegoddard42** [comment]
LGTM @Lukewh - can I just make one pedantic tweak? Can you make the "supported platforms" strip deep (is-deep)? Just to give it a bit more visual separation from the Raspberry Pi section. Thanks!

**Comment by davegoddard42** [comment]
This mustn't go live until /download/iot/risc-v (https://github.com/canonical/ubuntu.com/pull/11942) goes live.

**Comment by Lukewh** [comment]
> LGTM @Lukewh - can I just make one pedantic tweak? Can you make the "supported platforms" strip deep (is-deep)? Just to give it a bit more visual separation from the Raspberry Pi section. Thanks!

Consider it done (because I did it) :+1:

**Review by mtruj013 — APPROVED** [review]
LGTM, with just the tiniest note. Could you indent lines 123, 139, and 141? Not sure if it's just github being weird and showing them out of place like that

**Comment by Lukewh** [comment]
> LGTM, with just the tiniest note. Could you indent lines 123, 139, and 141? Not sure if it's just github being weird and showing them out of place like that

Good spot! Sorted.

**Pull request merged**
