### PR TITLE
[copy update] WD-5923 - updates on /ai/roadshow

### PR DESCRIPTION
**Pull request by pedoch**
## Done

- Copy update on `/ai/roadshow`

## QA

- Check out the [demo here](https://ubuntu-com-13117.demos.haus/ai/roadshow) and compare it with the changes requested in the [copy doc](https://docs.google.com/document/d/1CA0GUU6yRB65yfDaKi1dgN8DED2bDAFI2h-swSVtMtg/edit).

## Issue / Card

- [WD-5923](https://warthogs.atlassian.net/browse/WD-5923)

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

[WD-5923]: https://warthogs.atlassian.net/browse/WD-5923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by bartaz — APPROVED** [review]
LGTM (codewise)

**Comment by pedoch** [comment]
Hey @camillet16 could you please take a look at this PR when you can?

**Comment by camillet16** [comment]
@pedoch sorry this took time to get to.

Screen Shot 2023-08-31 at 12 37 56 PM
for the illustration change img src to https://assets.ubuntu.com/v1/9f6b6308-openstack+cloud+outlines+white.svg 

------

Screen Shot 2023-08-31 at 12 39 07 PM
format typography: add breakline(br) after the word "source"

-----

Screen Shot 2023-08-31 at 12 40 02 PM
Organize logos to below image:
Screen Shot 2023-08-31 at 12 40 45 PM

Best buy logo source: https://assets.ubuntu.com/v1/73f8db22-best-buy-logo.svg

----
Screen Shot 2023-08-31 at 12 46 23 PM

Organize logos to below image for visual balance:

Screen Shot 2023-08-31 at 12 46 08 PM

**Comment by camillet16** [comment]
Screen Shot 2023-08-31 at 2 15 34 PM
Can you edit the image to have a background rgba(0,0,0,0.03)
Image size: 351 height and have the width in ratio with the height.
Make the container flex and centralize the image

----
Screen Shot 2023-08-31 at 2 17 31 PM
For the logos can you edit it to the image below:
Screen Shot 2023-08-31 at 2 22 56 PM

Link for logos with variable width:
aws: https://assets.ubuntu.com/v1/4cd2ba24-aws-logo.svg
dell: https://assets.ubuntu.com/v1/fe17c507-dell-logo.svg
google: https://assets.ubuntu.com/v1/7577d797-google-logo.svg
hewlet packard: https://assets.ubuntu.com/v1/136e7089-hp-enterprise-logo.svg
Lenovo: https://assets.ubuntu.com/v1/a34e318a-lenovo-logo.svg
Microsoft Azure: https://assets.ubuntu.com/v1/3a7ece3a-microsoft-azure-new-logo.svg
Nvidia: https://assets.ubuntu.com/v1/d7829629-nvidia-logo.svg

They are 48px gap. They dont need to align with the grid.
height:144px per logo
you can make the container flex and have it when the screen goes smaller.

**Comment by camillet16** [comment]
LGTM. Thanks! @pedoch

**Pull request merged**
