### PR TITLE
Update k8s release cycle

### PR DESCRIPTION
**Pull request by stonepreston**
## Done

- Adds k8s 1.25 release information to chart
- Updates chart data to accurately reflect the N-2 and N-4 support windows. The start and end dates were also adjusted to match those provided in the [release notes](https://ubuntu.com/kubernetes/docs/release-notes) for the chart and the table
- Clarifies ESM support details 
- Canonical Kubernetes was changed to Charmed Kubernetes

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

Fixes #

## Screenshots

[If relevant, please include a screenshot.]

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

### CODE REVIEW

**Review by kwmonroe — APPROVED** [review]
LGTM for 1.25, thanks!

**Comment by stonepreston** [comment]
Moving to draft until we work out details regarding ESM support.

**Comment by mtruj013** [comment]
Thanks for taking this on @stonepreston and @kwmonroe! Could you update the [copy doc](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit) to reflect these changes as well? Usually changes are made there first and then requested for the page. Tagging @evilnick as well in case you'd like to take a look.

**Comment by evilnick** [comment]
hi @mtruj013, thanks for looking at this. I think there are some issues we need to clarify about exactly what the different support terms mean, so we will likely need to update the language further in the next few days

**Comment by mtruj013** [comment]
No worries @evilnick! I'll move this out of the review/qa pipeline for now then 🙂

**Comment by stonepreston** [comment]
@mtruj013 The PR is ready for review, and the copy doc has been updated with the new copy. Please let me know if you need anything else from me. Thanks!

**Review by mtruj013 — APPROVED** [review]
Sorry for the delay @stonepreston, LGTM! Thanks!

**Pull request merged**
