### PR TITLE
Update logos on /appliance/vm

### PR DESCRIPTION
**Pull request by petesfrench**
## Done

- Updates logos on /appliance/vm based on [this issue](https://warthogs.atlassian.net/browse/WD-1731)

## QA

- Go to https://ubuntu-com-12610.demos.haus/appliance/vm and check that it matches the 'replacement' image from the issue

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-1731

### CODE REVIEW

**Review by carkod — APPROVED** [review]

**Comment by lyubomir-popov** [comment]
blurry logo

**Comment by tbille** [comment]
@petesfrench @lyubomir-popov is it an issue with the asset or the code?

**Comment by petesfrench** [comment]
@camillet16 Could you give this a quick look and +1 please https://ubuntu-com-12610.demos.haus/appliance/vm

**Comment by camillet16** [comment]
@petesfrench demohaus says 404 :<

**Comment by camillet16** [comment]
@petesfrench false alarm I think it was still building. +1 added in 😄

**Pull request merged**
