### PR TITLE
K8s1.29+ck3 docs

### PR DESCRIPTION
**Pull request by evilnick**
## Done

- Updates various pages of K8s docs for 1.29+ck3 release

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
    
N.B. The content of these changes has already been reviewed

### CODE REVIEW

**Comment by lizzochek** [comment]
@evilnick where can I see the expected content for the pages and a full list of required changes?

**Comment by evilnick** [comment]
These are all the pages that are changed by this PR:

https://ubuntu-com-13997.demos.haus/kubernetes/docs/1.29/release-notes
https://ubuntu-com-13997.demos.haus/kubernetes/docs/1.29/upgrading
https://ubuntu-com-13997.demos.haus/kubernetes/docs/how-to-cos-lite
https://ubuntu-com-13997.demos.haus/kubernetes/docs/ldap
https://ubuntu-com-13997.demos.haus/kubernetes/docs/monitoring
https://ubuntu-com-13997.demos.haus/kubernetes/docs/release-notes
https://ubuntu-com-13997.demos.haus/kubernetes/docs/ceph
https://ubuntu-com-13997.demos.haus/kubernetes/docs/storage
https://ubuntu-com-13997.demos.haus/kubernetes/docs/upgrade-notes

There is no copy doc or anything for these pages, the sources are maintained in a different repository. You can see the history of the changes in [this PR](https://github.com/charmed-kubernetes/kubernetes-docs/pull/843)

Thanks for looking

**Comment by lizzochek** [comment]
Content looks good to me according to the PR you mentioned. Please fix listing errors and inclusive name check for me to review code

**Comment by evilnick** [comment]
@lizzochek I literally can't fix the inclusive language check.

e.g.
```
[keystone-auth]: https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/keystone-auth/using-client-keystone-auth.md
```
it's a URL :shrug: 

```
- `nrpe-external-master` (provides: `nrpe-external-master` on KCP and KW)
```
it's the name of a deprecated interface which we replaced, but people still need to know what the old one was called so they can update it.

I can't add  lines before these things because the Markdown parser used on u.c then interprets everything until the next blank line as HTML which obviously messes everything up. 

I will look at the jinja_lint test too, which I guess is new since we last updated K8s docs, but from a glance at the output it is complaining mostly about blank lines. The blank lines are usually only there to make the Markdown render properly, and, e.g. "The format for the `--storage` option is `<storage pool>,<size>,<number>`" is obviously not a collection of orphaned HTML tags. Any advice there appreciated!

**Comment by evilnick** [comment]
@lizzochek

I have removed some anchors the jinja2-lint was complaining about. All the other items are necessary either because they are references in code blocks, or blank lines to make the Markdown render properly. I think this test is misconfigured because it shouldn't really be running on Markdown files?

There is nothing else I can change on these pages to comply with the checks  which doesn't either break the rendering or remove important information.

**Review by kwmonroe — APPROVED** [review]
This looks great from a copy perspective, and as @evilnick notes, the woke check failures are expected due to external urls and the lint check failures are expected due to supposedly orphaned keys (even though they're syntactically correct in the code blocks) and blank lines for rendering purposes.

+1.

**Review by akbarkz — APPROVED** [review]

**Comment by evilnick** [comment]
Thanks @akbarkz

**Pull request merged**
