### PR TITLE
Meganav bug fixes

### PR DESCRIPTION
**Pull request by sowasred2012**
## Done

- Fixed a number of small bugs on the new meganav, including:
  - Fixed broken layout when transitioning between small and large breakpoints
  - Fixed keyboard navigation being impossible
  - Fixed opening "All Canonical" menu failing to close other open meganav sections

## QA

- Visit https://ubuntu-com-12390.demos.haus/
- Test the meganav at various breakpoints, the layout shouldn't break
- Test that you can navigate successfully via both mouse and keyboard
- Visit /openstack
- See that the meganav still works well in the "reduced" navigation view

## Issue / Card

Fixes https://github.com/canonical/web-squad/issues/6178

### CODE REVIEW

**Comment by anthonydillon** [comment]
On my phone there is a strange interaction when using the menu.

https://user-images.githubusercontent.com/1413534/210596634-3c1b873b-2418-4eda-99ad-aaede2c3c7a1.mp4

**Comment by anthonydillon** [comment]
QA issues:
- [ ] On https://ubuntu-com-12390.demos.haus/edge-computing there is no menu to select and so seems broken. We should hide the arrow if no navigation is available
- [ ] When logged in the username causes wrapping:
image

**Review by anthonydillon — CHANGES_REQUESTED** [review]
Code looks good but a few QA issues spotted

**Comment by sowasred2012** [comment]
@anthonydillon can you test for that interaction on your phone again? My phone didn't behave quite the same way - it still didn't behave correctly - but the issue now appears fixed for me.

**Review by anthonydillon — APPROVED** [review]
LGTM :+1:

**Pull request merged**
