### PR TITLE
GROWENG-3818 changing legacy google analytics event to datalayer push

### PR DESCRIPTION
**Pull request by laszlokajtar**
## Done

- Replaced legacy Google Analytics scripts with dataLayer.push() scripts.

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
- Upon the respective dyanmic form events, the dataLayer array contains the values specified in the code.

### CODE REVIEW

**Review by anthonydillon — APPROVED** [review]
LGTM

**Comment by carkod** [comment]
Can you fix `.js` code formatting? Looking [at this](https://github.com/canonical/ubuntu.com/actions/runs/9512102054/job/26219456514?pr=13954) you probably just need:

`prettier -w 'static/js/src/dynamic-forms.js'`
`prettier -w 'static/js/src/kernel-form.js'`

**Comment by laszlokajtar** [comment]
@carkod i don't think i have the proper setup to run the repo locally, so prettier actually gives me an error. i'm not sure how it'd reformat what i have, is this something i could do manually?

**Comment by carkod** [comment]
> @carkod i don't think i have the proper setup to run the repo locally, so prettier actually gives me an error. i'm not sure how it'd reformat what i have, is this something i could do manually?

Unfortunately prettier doesn't output what needs to be fixed, there's a [huge discussion about this](https://github.com/prettier/prettier/issues/6885)

**Comment by carkod** [comment]
@laszlokajtar should be fixed now, can you check that everything looks good? Thanks.

**Comment by laszlokajtar** [comment]
@carkod thank you!

**Pull request merged**
