### PR TITLE
WD-1721 WD-1720 WD-1722 Replace logos for /core pages

### PR DESCRIPTION
**Pull request by carkod**
## Done

Replace logos for /core pages

## QA

Check:
- https://ubuntu-com-12641.demos.haus/core [new images](https://warthogs.atlassian.net/browse/WD-1720?atlOrigin=eyJpIjoiZGQyNmVmZGRiOWIxNGViNWFiMzgzMGI5MzhlNjlkNGUiLCJwIjoiaiJ9)
- https://ubuntu-com-12641.demos.haus/core/services [new images](https://warthogs.atlassian.net/browse/WD-1721?atlOrigin=eyJpIjoiZWIyMjY4MDVjNTYwNDRlNThmNGU2MThjNTY1YTEwMzciLCJwIjoiaiJ9)
- https://ubuntu-com-12641.demos.haus/core/features [new images](https://warthogs.atlassian.net/browse/WD-1722?atlOrigin=eyJpIjoiMTIyZThlNzY3NDhjNGUyZWE0M2Q0NTM2YmM0MDdmMTkiLCJwIjoiaiJ9)

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-1721?atlOrigin=eyJpIjoiZWIyMjY4MDVjNTYwNDRlNThmNGU2MThjNTY1YTEwMzciLCJwIjoiaiJ9
Closes https://warthogs.atlassian.net/browse/WD-1720?atlOrigin=eyJpIjoiZGQyNmVmZGRiOWIxNGViNWFiMzgzMGI5MzhlNjlkNGUiLCJwIjoiaiJ9
Closes https://warthogs.atlassian.net/browse/WD-1722?atlOrigin=eyJpIjoiMTIyZThlNzY3NDhjNGUyZWE0M2Q0NTM2YmM0MDdmMTkiLCJwIjoiaiJ9

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

### CODE REVIEW

**Comment by petesfrench** [comment]
the ubuntu logo looks blury here:
image

**Comment by carkod** [comment]
> the ubuntu logo looks blury here: image

I replaced it with the other one, instead of the one provided by design. Can you take another look?

**Comment by petesfrench** [comment]
This is outside the scope of this work, but on medium-sized-screens this list is not centered:
image

**Review by petesfrench — APPROVED** [review]
LGTM, just one comment for a change outside the scope of this work

**Pull request merged**
