### PR TITLE
Redesign hackearth and opensource charts

### PR DESCRIPTION
**Pull request by petesfrench**
## Done

- Changes the design of the old hackearth and opensource charts to match the [new design](https://www.figma.com/file/wLOtPeQhAiExhQCwKYhi3H/24.04-U.com---desktop-(rebranding)?type=design&node-id=871-2991&mode=design&t=j9UhUNw14buKtrVZ-0)
- Refactors the code to be more readable and match the design pattern of other D3 charts
- Renames the `chart.js` file to `release-chart.js` and `release-chart.js` to `release-chart-manager.js` as I think it is more clear what these files contain

## QA

- Check that the chart matches the design
- Check it works on all screen sizes (on mobile it should disappear and be a table)
- Check the code looks good 
- Check the file name changes make sense and add more clarity

DESIGN:
image

D3 REPRODUCTION:
image

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-8437

### CODE REVIEW

**Comment by lyubomir-popov** [comment]
looks great thanks @petesfrench. Could I ask you for a drive by fix of these double gray lines in a chart further up:
image

**Comment by lyubomir-popov** [comment]
sorry just noticed this on smaller screens

**Comment by petesfrench** [comment]
@lyubomir-popov The image you uploaded isn't working for me. However, I have made changes that I suspect will fix the problem.

**Review by muhammadbassiony — APPROVED** [review]
LGTM 🚀

**Pull request merged**
