### PR TITLE
Issue #13093 and #13091 fixed

### PR DESCRIPTION
**Pull request by Harsh0707005**
Fixed issue #13091  and  #13093 , which were to modify sitemap.xml to improve seo index reachability and starting search operation when pressed enter key in text field.

Checked and verified the changes made

### CODE REVIEW

**Comment by carkod** [comment]
Thank you for the contribution! We already fixed the issue of the sitemap. The issue of pressing enter to submit the search form will require UX approval.

**Comment by carkod** [comment]
> @carkod My PR has not been merged for "pressing enter to submit the search form", so how will UX team approve, Do i have to open another PR for the issue #13093 ??

We assigned a UX designer to take a look, then we'll get back to you.

**Comment by Harsh0707005** [comment]
> > @carkod My PR has not been merged for "pressing enter to submit the search form", so how will UX team approve, Do i have to open another PR for the issue #13093 ??
> 
> We assigned a UX designer to take a look, then we'll get back to you.

But the PR has been closed, can it be still merged into main, if UX team finds it valid?

**Comment by juanruitina** [comment]
This was flagged up in #12478 and #13093, I agree that it should submit on enter. @carkod

**Comment by Harsh0707005** [comment]
> This was flagged up in #12478 and #13093, I agree that it should submit on enter. @carkod
@carkod

**Pull request closed without merging**
