### PR TITLE
Copy update /download/desktop/thank-you

### PR DESCRIPTION
**Pull request by steverydz**
## Done
**DON'T MERGE** until 26th Jan
Updated the copy on the desktop download thank you page

## QA
- Go to https://ubuntu-com-12417.demos.haus/desktop
- Download Ubuntu so you can see the thank you page
- Check that the changes requested in [the copy doc](https://docs.google.com/document/d/187Vg9I0Jjlp1_yAjYtHdoEwFCJeVOaz9Kzeb6kptMpA/edit) have been made
- Resolve the comments in the copy doc

## Issue / Card

Fixes https://github.com/canonical/marketplace-tribe/issues/2953

### CODE REVIEW

**Comment by codeEmpress1** [comment]
LGTM!

**Comment by ClementChaumel** [comment]
image
This link leads to a 404. It's the same on the copydoc but I thought I'd check

**Comment by steverydz** [comment]
> This link leads to a 404. It's the same on the copydoc but I thought I'd check

@petesfrench @mtruj013 is this page meant to be live at the moment?

**Comment by petesfrench** [comment]
@steverydz I will check with Oliver and get back to you

**Comment by steverydz** [comment]
@petesfrench I've updated this with the removed whitepaper link

**Comment by petesfrench** [comment]
@steverydz Awesome, thank you for your help!

**Comment by petesfrench** [comment]
hey @steverydz, sorry for the the back and fourth, but can you add that link back please. This page is to be released on the 26th Jan, when that engage page will be available

**Comment by steverydz** [comment]
> hey @steverydz, sorry for the the back and fourth, but can you add that link back please. This page is to be released on the 26th Jan, when that engage page will be available

Done

**Pull request merged**
