### PR TITLE
chore(/gcp): Update content

### PR DESCRIPTION
**Pull request by petesfrench**
## Done

- [copydoc](https://docs.google.com/document/d/1Gvt9tNFDZkqkBcP0k79C6ueTJCmNZvwoXQoU19WEa8E/edit?tab=t.0)

## QA

- Check out [the demo](https://ubuntu-com-14562.demos.haus/gcp)
- Compare to content changes in the [copydoc](https://docs.google.com/document/d/1Gvt9tNFDZkqkBcP0k79C6ueTJCmNZvwoXQoU19WEa8E/edit?tab=t.0)

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-17456

### CODE REVIEW

**Review by fasih-mehmood — COMMENTED** [review]
@petesfrench Looks good. I mentioned you under some comments in the copy doc, could you implement those as well please? Thanks!

**Comment by petesfrench** [comment]
@fasih-mehmood It seems my find and replace was not greedy enough in this case. I have updated accordingly

**Comment by fasih-mehmood** [comment]
> @fasih-mehmood It seems my find and replace was not greedy enough in this case. I have updated accordingly

Thank you!

**Review by fasih-mehmood — COMMENTED** [review]
@petesfrench It looks like the changes were reverted

**Review by fasih-mehmood — COMMENTED** [review]
This is all thats left now

image

**Comment by petesfrench** [comment]
@fasih-mehmood Apologies, not sure why my changes aren't being picked up

**Review by fasih-mehmood — APPROVED** [review]

**Pull request merged**
