### PR TITLE
Upgrade to Vanilla 4.3

### PR DESCRIPTION
**Pull request by bartaz**
## Done

- Updates Vanilla to 4.3
- Updates cookie policy to 3.5 (to support Vanilla 4)
- Updates width of global nav (to fit new grid width in Vanilla 4)
- **DOES NOT** update global nav version (as this is tied to meganav work)

Drive-by: 
- added missing root element for logo section on the home page

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
- ⚠️ Review as many pages/templates as possible against [Vanilla migration guide](https://vanillaframework.io/docs/migration-guide-to-v4)
- Review the pages with broken logo strips and make sure they look decent (no need to be perfectly aligned, but just not look broken):
      - **NOTE**: logo sections are meant to be left aligned now, so the fact of them not being centered is not a bug
      - https://ubuntu-com-13131.demos.haus/embedding
      - https://ubuntu-com-13131.demos.haus/financial-services
      - https://ubuntu-com-13131.demos.haus/internet-of-things
      - https://ubuntu-com-13131.demos.haus/internet-of-things/appstore
      - https://ubuntu-com-13131.demos.haus/kubernetes
      - https://ubuntu-com-13131.demos.haus/openstack/support
      - https://ubuntu-com-13131.demos.haus/automotive
      - https://ubuntu-com-13131.demos.haus/azure
      - https://ubuntu-com-13131.demos.haus/robotics/ros-esm
      - https://ubuntu-com-13131.demos.haus/robotics/what-is-ros
      - https://ubuntu-com-13131.demos.haus/internet-of-things/smart-city
      - https://ubuntu-com-13131.demos.haus/telco/vnf
      - https://ubuntu-com-13131.demos.haus/telco/cnf
      - https://ubuntu-com-13131.demos.haus/telco/openran
      - https://ubuntu-com-13131.demos.haus/telco/magma
      - https://ubuntu-com-13131.demos.haus/kubernetes/what-is-kubernetes
      - https://ubuntu-com-13131.demos.haus/landscape
      - https://ubuntu-com-13131.demos.haus/robotics
      - https://ubuntu-com-13131.demos.haus/security
      - https://ubuntu-com-13131.demos.haus/ai
      - https://ubuntu-com-13131.demos.haus/ai/what-is-kubeflow
      - https://ubuntu-com-13131.demos.haus/ceph/what-is-ceph
      - https://ubuntu-com-13131.demos.haus/managed
      - https://ubuntu-com-13131.demos.haus/openstack
      - https://ubuntu-com-13131.demos.haus/openstack/managed
      - https://ubuntu-com-13131.demos.haus/core
      - https://ubuntu-com-13131.demos.haus/desktop/features
      - https://ubuntu-com-13131.demos.haus/telco
      - https://ubuntu-com-13131.demos.haus/openstack/consulting
      - https://ubuntu-com-13131.demos.haus/openstack/features
      - https://ubuntu-com-13131.demos.haus/aws
      - https://ubuntu-com-13131.demos.haus/edge-computing
      - https://ubuntu-com-13131.demos.haus/gov
      - https://ubuntu-com-13131.demos.haus/hpc
      - https://ubuntu-com-13131.demos.haus/hpc/use-cases
      - https://ubuntu-com-13131.demos.haus/managed/apps/kafka
      - https://ubuntu-com-13131.demos.haus/managed/apps
      - https://ubuntu-com-13131.demos.haus/observability
      - https://ubuntu-com-13131.demos.haus/observability/managed
      - https://ubuntu-com-13131.demos.haus/security/livepatch
      - https://ubuntu-com-13131.demos.haus/server
      - https://ubuntu-com-13131.demos.haus/rfp

## Issue / Card

Replaces previous testing PR #12791

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

### CODE REVIEW

**Review by mtruj013 — CHANGES_REQUESTED** [review]
Not all, but some logo sections look wonky:

https://ubuntu-com-13131.demos.haus/openstack
image

https://ubuntu-com-13131.demos.haus/openstack/features:
image

https://ubuntu-com-13131.demos.haus/openstack/managed:
image

https://ubuntu-com-13131.demos.haus/kubernetes
image

**Comment by bartaz** [comment]
> Not all, but some logo sections look wonky:

Yes, that's an issue with logo section changes we introduced in 4.2 if logo section doesn't use images correctly spaced by visual design.

Currently the easiest approach is use Vanilla 4.1.

We may add a fallback variant to logo section to address this later, but still it would be a good point to start using correctly spaced images in logo section.

**Comment by bartaz** [comment]
Broken logo strips (via [QA document](https://docs.google.com/spreadsheets/d/1m8f-9FPbIsc-wfGKwCC9o3wBZhEk-fgI7EY04NBqxUI/edit#gid=1569331356))

https://ubuntu-com-13131.demos.haus/embedding
https://ubuntu-com-13131.demos.haus/financial-services
https://ubuntu-com-13131.demos.haus/internet-of-things
https://ubuntu-com-13131.demos.haus/internet-of-things/appstore
https://ubuntu-com-13131.demos.haus/kubernetes
https://ubuntu-com-13131.demos.haus/openstack/support
https://ubuntu-com-13131.demos.haus/automotive
https://ubuntu-com-13131.demos.haus/azure
https://ubuntu-com-13131.demos.haus/robotics/ros-esm
https://ubuntu-com-13131.demos.haus/robotics/what-is-ros
https://ubuntu-com-13131.demos.haus/internet-of-things/smart-city
https://ubuntu-com-13131.demos.haus/telco/vnf
https://ubuntu-com-13131.demos.haus/telco/cnf
https://ubuntu-com-13131.demos.haus/telco/openran
https://ubuntu-com-13131.demos.haus/telco/magma
https://ubuntu-com-13131.demos.haus/kubernetes/what-is-kubernetes
https://ubuntu-com-13131.demos.haus/landscape
https://ubuntu-com-13131.demos.haus/robotics
https://ubuntu-com-13131.demos.haus/security
https://ubuntu-com-13131.demos.haus/ai
https://ubuntu-com-13131.demos.haus/ai/what-is-kubeflow
https://ubuntu-com-13131.demos.haus/ceph/what-is-ceph
https://ubuntu-com-13131.demos.haus/managed
https://ubuntu-com-13131.demos.haus/openstack
https://ubuntu-com-13131.demos.haus/openstack/managed
https://ubuntu-com-13131.demos.haus/core
https://ubuntu-com-13131.demos.haus/desktop/features
https://ubuntu-com-13131.demos.haus/telco
https://ubuntu-com-13131.demos.haus/openstack/consulting
https://ubuntu-com-13131.demos.haus/openstack/features

**Comment by juanruitina** [comment]
The logos on the pages listed above certainly look better now, although there are several instances of blurry logos (they aren't blurry on the live website).

Some examples:

In https://ubuntu-com-13131.demos.haus/telco

Screenshot 2023-09-13 at 13 34 55

In https://ubuntu-com-13131.demos.haus/financial-services

Screenshot 2023-09-13 at 13 37 44

Screenshot 2023-09-13 at 13 32 32

In https://ubuntu-com-13131.demos.haus/kubernetes

Screenshot 2023-09-13 at 13 32 15

Can we address this? In any case, I'd defer to Lyubo for reviewing this, as it's for Visual to decide what's good enough.

**Comment by bartaz** [comment]
> The logos on the pages listed above certainly look better now, although there are several instances of blurry logos. They aren't blurry on the live website, they look smaller there, it seems some style is overriding image size.

Good catch. Yes, it seems that some images are rendered bigger than declared in HTML, I should be able to address that.

**Comment by lyubomir-popov** [comment]
@bartaz Can we have 2rem margin-bottom on thios version? .5 is too little for logos that have no white space above/below inside the image itself. Up to you whether to put that in vanilla or locally here.

**Comment by lyubomir-popov** [comment]
This looks very different compared to the vanilla example:
image
 
Why is the paragraph not aligned with the heading?

**Comment by lyubomir-popov** [comment]
I think it looks acceptable, safe for the two things mentioned above ^.

**Comment by bartaz** [comment]
> @bartaz Can we have 2rem margin-bottom on thios version? .5 is too little for logos that have no white space above/below inside the image itself. Up to you whether to put that in vanilla or locally here.

@lyubomir-popov Do you mean margin below each image, or below the whole logo section component?
 
> Some logos are still blurry. For this version of the logo section (with the added class), I wonder if we can maybe set a lower max-height? Instead of 8rem, maybe 5rem for example?

Blurred images are likely because of too small size in HTML, causing cloudinary to serve smaller images, stretched by CSS. It would be best to list them and fix if needed. It's hard to identify them myself.

Max-height wont work, it would screw the aspect ratio of images, because they have fixed width in this version of logo section.




> This looks very different compared to the vanilla example: image
> 
> Why is the paragraph not aligned with the heading? https://ubuntu-com-13131.demos.haus/openstack/consulting

This is mixing stepped list and grid in way we don't support in Vanilla. Not sure what to do with that without rebuilding it in a different way. We don't have an example in Vanilla of stepped list with text and images on the side.

**Comment by bartaz** [comment]
@lyubomir-popov Even if I try to align it following Vanilla docs, it doesn't. I can't figure out why. It seems that something in ubuntu.com custom styles gets in the way.

Screenshot 2023-09-14 at 10 49 50

**Review by mtruj013 — APPROVED** [review]
Looks like there are a couple of linting errors, but other than that LGTM!

**Comment by bartaz** [comment]
> Looks like there are a couple of linting errors, but other than that LGTM!

Oh, sorry, they've been "under the fold" on the list of CI checks in GitHub ;)
I'll look into fixing them.

**Comment by lyubomir-popov** [comment]
> @lyubomir-popov Even if I try to align it following Vanilla docs, it doesn't. I can't figure out why. It seems that something in ubuntu.com custom styles gets in the way.
> 
> Screenshot 2023-09-14 at 10 49 50

ok, please leave it. We'll improve it when we rebrand the page and get rid of all the local legacy styles.

**Review by carkod — APPROVED** [review]
LGTM. I created a ticket for componetizing the logos that repeat the code https://warthogs.atlassian.net/browse/WD-6296

**Pull request merged**
