### PR TITLE
Update to vanilla-3.13.0

### PR DESCRIPTION
**Pull request by petesfrench**
## Done

[This PR](https://github.com/canonical/ubuntu.com/pull/12667) already exists, but I wanted to get the vanilla update live asap as it is required for [this PR](https://github.com/canonical/ubuntu.com/pull/12675) that is due to go live today

- Updates to vanilla-3.13.0. This is a separate PR

## QA

- Check the changes made to the nav

### CODE REVIEW

**Comment by petesfrench** [comment]
There appears to be an issue with the `is-split` class for `p-list`. Unless this is intentional @bartaz @lyubomir-popov?:
3.12.1
image
3.13.0
image

**Comment by petesfrench** [comment]
This was on https://ubuntu.com/openstack/features.

I tried adding more text on live to see if the same thing would happen and this was the result:
Screenshot from 2023-04-03 09-52-22

**Comment by petesfrench** [comment]
Awesome, will do. Thanks for your help on this @bartaz !

**Review by pedoch — APPROVED** [review]
LGTM! 👍

**Pull request merged**
