### PR TITLE
WD-8067 - page update for iot

### PR DESCRIPTION
**Pull request by lizzochek**
## Done

Update /internet-of-things page according to copy doc

## QA

- [demo link](https://ubuntu-com-13518.demos.haus/internet-of-things)
- [copy doc](https://docs.google.com/document/d/1nBx1SP3Y10gXX0rZPDaz1Gudy-hWP4XRMUcETyPBldI/edit)
- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/
- Run through the following [QA steps](https://discourse.canonical.com/t/qa-steps/152)
- Check that the links and text are correct

## Issue / Card
[WD-8067](https://warthogs.atlassian.net/browse/WD-8067)

Fixes #

## Screenshots

[WD-8067]: https://warthogs.atlassian.net/browse/WD-8067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by mtruj013 — APPROVED** [review]
LGTM! Left a question for @Sophie-32 on the doc regarding the images. Not sure if the pdm actually did want these to be clickable or if she added the links in the wrong place accidentally

**Comment by Sophie-32** [comment]
Might be my mistake, but I don't see 'Learn more about Ubuntu Core' on the copydoc, do you know where you added that from?

**Comment by lizzochek** [comment]
@Sophie-32 I didn't, it was already there. Removed it now, please check again

**Comment by juanruitina** [comment]
Small suggestion: given that the "Discover Ubuntu IoT in your industry" section operates as a navigation, let's add a chevron to every heading so it's clear it's not just a heading, but also a link. Please, also make them H3 instead of H2s (keep the styling), they are under an H2 already.

**Pull request merged**
