### PR TITLE
Meganav prototype v2

### PR DESCRIPTION
**Pull request by sowasred2012**
## Done

- Added v2 of the mega nav prototype, the first of two variants (the second is [here](https://github.com/canonical-web-and-design/ubuntu.com/pull/11292))
  - This one features a "left hand side" layout on the products dropdown
 
**Not to be merged - for demo purposes only**

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/

## Issue / Card

Fixes https://github.com/canonical-web-and-design/web-squad/issues/4834

### CODE REVIEW

**Comment by sowasred2012** [comment]
@lyubomir-popov @davegoddard42 I've updated this prototype according to our earlier conversation - take a look, let me know if there are other changes and/or if you want these changes applied to the other prototype as well.

**Comment by sowasred2012** [comment]
@lyubomir-popov @davegoddard42 - I had a quick catch up with Dave earlier, and I've implemented the feedback we talked about:
- the `small` copy below a lot of the links is now `#aaa`
- tweaked the style of the "View all" link to match the design
- updated the links and replaced lorem ipsum based on what's in the [spreadsheet](https://docs.google.com/spreadsheets/d/1CrbFol2QrGp-QQeYAhFk1At3BCQl5iZhW6j9OZoRI5k/edit#gid=887562705)
- added dividing lines between the items in the right hand panel of the Use Case menu

**Comment by lyubomir-popov** [comment]
@sowasred2012 I pushed a pr for the font weight, a few more thoughts:
- the inverted link component will get an underline in a planned update, so I would use a bespoke meganav-scoped class for the white links in there
- the orange highlight on the top nav shouls be white in the new design, but mybe this will change in the base component, not sure if this will need to go live before vanilla releases the update in time

**Comment by minkyngkm** [comment]
@lyubomir-popov could you take a look at this?

**Pull request closed without merging**
