### PR TITLE
[WD-7913] support portal legal pages

### PR DESCRIPTION
**Pull request by akbarkz**
## Done

- Add a Data Privacy and a Terms and Policies pages for Support Portal according to the following copy docs:
   - https://docs.google.com/document/d/1x8vH0dabSF7en7KenZKKDlugFHjbKwtdonuKPbQUDiM/edit
   - https://docs.google.com/document/d/1AlOE2_-BqZNP4hiiuf8kZney8g1zvqAlDYl2u3X6m6I/edit
   - https://docs.google.com/document/d/1ugZ-7R6qSYSKjofiPicy444c5zXho81J3Z_f-hpCcZc/edit
   - https://docs.google.com/document/d/1p3ZWroZ3nkw8XJJdPvPxSlWGYcLZLT8UbUVuppBcyHk/edit

## QA

- Check out this feature branch
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
    - Be sure to test on mobile, tablet and desktop screen sizes
- Navigate to https://ubuntu-com-13426.demos.haus/legal/data-privacy and check if it has a new link that takes to Support Portal Data Privacy page.
    - Check the content of a new page at https://ubuntu-com-13426.demos.haus/legal/data-privacy/support-portal
- Navigate to https://ubuntu-com-13426.demos.haus/legal/terms-and-policies and check if it has a new link that takes to Support Portal Terms and Policies page.
    - Check the content of a new page at https://ubuntu-com-13426.demos.haus/legal/terms-and-policies/support-portal

## Issue / Card

Fixes https://warthogs.atlassian.net/browse/WD-7913

## Help

[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

### CODE REVIEW

**Comment by Sophie-32** [comment]
Can I make some spacing recommendations for the first paragraph? Also suggest a table of contents to help readers see what's on this page and navigate through it more quickly.

**Comment by akbarkz** [comment]
@Sophie-32 Thanks for having a look. Your suggestions make totals sense, however these 2 new pages are implemented in accordance to every other similar page under /legal/data-privacy and /legal/terms-and-policies. If we are to change the new ones, I believe we need to change all the other existing ones the same way. 
Considering the urgency of this task I suggest we leave it as it is, but feel free to contact Lydia and suggest your changes. If she agrees we can add another task to our backlog. Wdyt?

**Comment by Sophie-32** [comment]
> @Sophie-32 Thanks for having a look. Your suggestions make total sense, however these 2 new pages are implemented in accordance to every other similar page under /legal/data-privacy and /legal/terms-and-policies. If we are to change the new ones, I believe we need to change all the other existing ones the same way. Considering the urgency of this task I suggest we leave it as it is, but feel free to contact Lydia and suggest your changes. If she agrees we can add another task to our backlog. Wdyt?

Yes that makes sense!

**Review by carkod — APPROVED** [review]
LGTM, I couldn't compare with the other two copy docs because I didn't have permission to view them. I think you may want to add at least view permissions next time you create a copy doc, or maybe it's a folder issue.

**Pull request merged**
